// Code generated by generate_terminal_protocol_contract.py. DO NOT EDIT.
package protocolvalue

import (
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/plumliu/pulsara-agent/clients/terminal/internal/protocol"
	"github.com/plumliu/pulsara-agent/clients/terminal/internal/publictext"
	"google.golang.org/protobuf/proto"
)

const (
	MaximumActiveQueueItems      = 64
	MaximumServerNotifications   = 16
	MaximumOperationalActivities = 256
	MaximumOperationalBytes      = 1024 * 1024
)

type Bootstrap struct {
	LaunchID         string
	ClientInstanceID string
	HostSessionID    string
	RuntimeSessionID string
	SocketPath       string
	LaunchCapability []byte
	ParentPID        uint64
	ExpiresAt        time.Time
	Fingerprint      string
}

type HandshakeCandidate struct {
	ID                          string
	ClientInstanceID            string
	AttachmentAttemptGeneration uint64
	HostSessionID               string
	RuntimeSessionID            string
	Fingerprint                 string
}

type TransportAuthResult struct {
	RequestID                  string
	AttemptID                  string
	ConnectionID               string
	ClientInstanceID           string
	CredentialID               string
	Disposition                protocol.TransportAuthDisposition
	CandidateFingerprint       string
	ResultFingerprint          string
	RecoveredAttachmentPresent bool
}

type TransportBinding struct {
	AttachmentID         string
	AttachmentGeneration uint64
	ConnectionID         string
	Generation           uint64
	BoundAtUTC           string
	Fingerprint          string
}

type RecoveredAttachmentTransportBinding struct {
	PreviousBindingFingerprint string
	ResultingBinding           TransportBinding
	Disposition                protocol.AttachmentTransportRebindDisposition
	ReceiptFingerprint         string
}

type RecoveredAttachAcknowledgement struct {
	Ack     ValidatedAttachAckResult
	Binding RecoveredAttachmentTransportBinding
}

type NegotiatedLimits struct {
	MaximumFrameBytes                  uint32
	MaximumHistoryPageCells            uint32
	MaximumHistoryPageDecodedBytes     uint32
	MaximumObservationWaitMS           uint32
	SecretFrameMaximumBytes            uint32
	MaximumActiveQueueItems            uint32
	MaximumServerControlNotifications  uint32
	MaximumOperationalActivityCells    uint32
	MaximumDurableObservationBytes     uint32
	MaximumOperationalObservationBytes uint32
	MaximumControlObservationBytes     uint32
	MaximumObservationBatchBytes       uint32
}

type HelloNegotiationWinner struct {
	CandidateID                  string
	CandidateFingerprint         string
	AttachmentAttemptGeneration  uint64
	SelectedProtocolMajor        uint32
	SelectedProtocolMinor        uint32
	SelectedSchemaFingerprint    string
	SelectedCapabilities         []protocol.TerminalClientCapability
	Limits                       NegotiatedLimits
	CapabilityFingerprint        string
	NegotiationTranscript        string
	NegotiationWinnerFingerprint string
}

type ValidatedServerHelloReceipt struct {
	RequestID                    string
	TransportAuthAttemptID       string
	CandidateID                  string
	CandidateFingerprint         string
	NegotiationWinnerFingerprint string
	CurrentConnectionID          string
	ChallengeCommitment          string
	ReceiptFingerprint           string
	PreparedChallengeHandleID    string
}

type HandshakeCandidateTerminalReceipt struct {
	CandidateID                       string
	CandidateFingerprint              string
	AttachmentAttemptGeneration       uint64
	TerminalDisposition               protocol.HandshakeCandidateTerminalDisposition
	TerminalReason                    protocol.HelloCandidateTerminalReason
	RequiredClientDisposition         protocol.HelloCandidateClientDisposition
	PriorNegotiationWinnerFingerprint string
	HasPriorNegotiationWinner         bool
	CandidateRegistryRevision         uint64
	TerminalReceiptFingerprint        string
}

type HelloNegativeKind uint8

const (
	HelloNegotiationUnavailable HelloNegativeKind = iota + 1
	HelloRejected
)

type HelloNegativeOutcome struct {
	Kind                   HelloNegativeKind
	RequestID              string
	TransportAuthAttemptID string
	CurrentConnectionID    string
	CandidateID            string
	CandidateFingerprint   string
	TerminalReceipt        HandshakeCandidateTerminalReceipt
	OutcomeFingerprint     string
}

func (v HelloNegativeOutcome) RequiresParentRelaunch() bool {
	return v.TerminalReceipt.RequiredClientDisposition == protocol.HelloCandidateClientDisposition_PARENT_RELAUNCH_NEW_CANDIDATE
}

func (v HelloNegativeOutcome) FatalCompatibility() bool {
	return v.TerminalReceipt.RequiredClientDisposition == protocol.HelloCandidateClientDisposition_FATAL_COMPATIBILITY
}

type HeartbeatPolicy struct {
	Interval           time.Duration
	Grace              time.Duration
	MaximumMissedCount uint32
}

type Attachment struct {
	ClientInstanceID            string
	AttachmentAttemptGeneration uint64
	ConnectionID                string
	BindingGeneration           uint64
	BindingFingerprint          string
	ID                          string
	RuntimeSessionID            string
	Generation                  uint64
	Role                        protocol.AttachmentRole
	ControllerGeneration        uint64
	IssuedAt                    time.Time
	ExpiresAt                   time.Time
	IdentityFingerprint         string
	SemanticWinnerFingerprint   string
	CurrentReceiptFingerprint   string
	ControllerDisposition       protocol.ControllerDisposition
	BootstrapRequirement        protocol.BootstrapRequirement
	Heartbeat                   HeartbeatPolicy
}

type AttachReceipt struct {
	RequestID                  string
	TransportAuthAttemptID     string
	CandidateID                string
	CandidateFingerprint       string
	SemanticWinnerFingerprint  string
	CurrentBinding             TransportBinding
	PreviousBindingFingerprint string
	HasPreviousBinding         bool
	Disposition                protocol.AttachResultDisposition
	ReceiptFingerprint         string
}

type ValidatedAttachAckResult struct {
	RequestID                      string
	AttachmentID                   string
	AttachmentGeneration           uint64
	SemanticWinnerFingerprint      string
	AcknowledgedBindingFingerprint string
	Disposition                    protocol.AttachAckDisposition
	RetiredCredentialID            string
	ResultFingerprint              string
}

type PreparedHeartbeatRequest struct {
	RequestID                     string
	RuntimeSessionID              string
	AttachmentID                  string
	AttachmentGeneration          uint64
	AttachmentIdentityFingerprint string
	SemanticWinnerFingerprint     string
	CurrentBinding                TransportBinding
	HeartbeatGeneration           uint64
	PreviousAcceptedGeneration    uint64
	CandidateFingerprint          string
	RequestFingerprint            string
}

type PreparedOperationalSnapshotRequest struct {
	RequestID                     string
	RuntimeSessionID              string
	AttachmentID                  string
	AttachmentGeneration          uint64
	AttachmentIdentityFingerprint string
	CurrentBinding                TransportBinding
	RequestedAfterGeneration      uint64
	RequestedAfterCursor          uint64
	RequestFingerprint            string
}

type ValidatedHeartbeatAcceptedReceipt struct {
	RequestID                      string
	RuntimeSessionID               string
	AttachmentID                   string
	AttachmentGeneration           uint64
	AttachmentIdentityFingerprint  string
	SemanticWinnerFingerprint      string
	AcknowledgedBindingFingerprint string
	HeartbeatGeneration            uint64
	PreviousAcceptedGeneration     uint64
	CandidateFingerprint           string
	LeaseExpiresAt                 time.Time
	LivenessDisposition            protocol.HeartbeatLivenessDisposition
	SemanticResultFingerprint      string
	ReceiptFingerprint             string
}

type ValidatedHeartbeatRejectedReceipt struct {
	RequestID                     string
	RuntimeSessionID              string
	AttachmentID                  string
	AttachmentGeneration          uint64
	AttachmentIdentityFingerprint string
	SemanticWinnerFingerprint     string
	SubmittedBindingFingerprint   string
	HeartbeatGeneration           uint64
	PreviousAcceptedGeneration    uint64
	CandidateFingerprint          string
	Reason                        protocol.HeartbeatRejectedReason
	SemanticResultFingerprint     string
	ReceiptFingerprint            string
}

type HistoryCell struct {
	ID          string
	Revision    uint64
	Kind        string
	PublicText  string
	Fingerprint string
}

type QueueItem struct {
	ID                    string
	AcceptedOrdinal       uint64
	PublicPreview         string
	HeadEventID           string
	Revision              uint64
	DeliveryState         protocol.PromptQueueDeliveryState
	RequestedDeliveryMode protocol.PromptQueueRequestedDeliveryMode
	ResolvedDeliveryMode  protocol.PromptQueueResolvedDeliveryMode
	Fingerprint           string
}

type ServerNotification struct {
	ID          string
	Ordinal     uint64
	Kind        protocol.ServerNotificationKind
	PublicText  string
	Fingerprint string
}

type ControlProjection struct {
	RuntimeSessionID                  string
	Generation                        uint64
	Revision                          uint64
	ProjectionFingerprint             string
	TransitionAccumulator             string
	RegistryFingerprint               string
	CursorFingerprint                 string
	SnapshotFingerprint               string
	ViewFingerprint                   string
	SessionLifecycle                  protocol.TerminalSessionLifecycleState
	ActiveRunID                       string
	PendingInteraction                bool
	PendingInteractionID              string
	PendingInteractionGeneration      uint64
	PendingInteractionViewFingerprint string
	QueueHeadFingerprint              string
	QueueViewFingerprint              string
	QueueAccountRevision              uint64
	QueueAccumulator                  string
	QueueItems                        []QueueItem
	NotificationAccumulator           string
	ServerNotifications               []ServerNotification
}

type DurableSnapshot struct {
	RequestID             string
	HostSessionID         string
	RuntimeSessionID      string
	AuthorityHighWater    uint64
	ProjectionRevision    uint64
	ActiveHeadFingerprint string
	Control               ControlProjection
	Cells                 []HistoryCell
	SnapshotFingerprint   string
}

type OperationalCell struct {
	OwnerKind       string
	OwnerID         string
	OwnerGeneration uint64
	PublicText      string
	Fingerprint     string
}

type OperationalSnapshot struct {
	RequestID                      string
	RuntimeSessionID               string
	AttachmentID                   string
	AttachmentGeneration           uint64
	AttachmentIdentityFingerprint  string
	AcknowledgedBindingFingerprint string
	Generation                     uint64
	Cursor                         uint64
	Cells                          []OperationalCell
	Count                          uint32
	EncodedBytes                   uint64
	Accumulator                    string
	StateFingerprint               string
	ContractFingerprint            string
	FrameFingerprint               string
}

func TransportAuthResultFromProto(value *protocol.TerminalTransportAuthResult) (TransportAuthResult, error) {
	if value == nil || value.AuthRequestId == "" || value.AuthAttemptId == "" || value.ConnectionId == "" || value.ClientInstanceId == "" || value.CredentialId == "" || value.ResultFingerprint == "" {
		return TransportAuthResult{}, errors.New("terminal transport authentication proof is incomplete")
	}
	if err := protocol.ValidateFingerprint("terminal-transport-auth-result:v1", value, "result_fingerprint", value.ResultFingerprint); err != nil {
		return TransportAuthResult{}, err
	}
	switch value.Disposition {
	case protocol.TransportAuthDisposition_TRANSPORT_AUTHENTICATED,
		protocol.TransportAuthDisposition_TRANSPORT_COMPATIBLE_AUTH_WINNER:
		if value.AuthenticatedCandidateFingerprint == nil || value.RecoveredAttachAckResult != nil || value.RecoveredTransportBinding != nil || value.PublicRejectionCode != nil {
			return TransportAuthResult{}, errors.New("terminal ordinary auth result matrix is invalid")
		}
	case protocol.TransportAuthDisposition_TRANSPORT_ACK_RESULT_RECOVERY:
		if value.AuthenticatedCandidateFingerprint == nil || value.RecoveredAttachAckResult == nil || value.RecoveredTransportBinding == nil || value.PublicRejectionCode != nil {
			return TransportAuthResult{}, errors.New("terminal ACK recovery result matrix is invalid")
		}
	case protocol.TransportAuthDisposition_TRANSPORT_AUTHENTICATION_REJECTED:
		if value.PublicRejectionCode == nil || value.AuthenticatedCandidateFingerprint != nil || value.RecoveredAttachAckResult != nil || value.RecoveredTransportBinding != nil {
			return TransportAuthResult{}, errors.New("terminal auth rejection matrix is invalid")
		}
	default:
		return TransportAuthResult{}, errors.New("terminal transport authentication disposition is unknown")
	}
	candidate := ""
	if value.AuthenticatedCandidateFingerprint != nil {
		candidate = *value.AuthenticatedCandidateFingerprint
	}
	return TransportAuthResult{
		RequestID: value.AuthRequestId, AttemptID: value.AuthAttemptId,
		ConnectionID: value.ConnectionId, ClientInstanceID: value.ClientInstanceId,
		CredentialID: value.CredentialId, Disposition: value.Disposition,
		CandidateFingerprint: candidate, ResultFingerprint: value.ResultFingerprint,
		RecoveredAttachmentPresent: value.RecoveredAttachAckResult != nil || value.RecoveredTransportBinding != nil,
	}, nil
}

func RecoveredAttachAcknowledgementFromProto(value *protocol.TerminalTransportAuthResult) (RecoveredAttachAcknowledgement, error) {
	if value == nil || value.Disposition != protocol.TransportAuthDisposition_TRANSPORT_ACK_RESULT_RECOVERY || value.RecoveredAttachAckResult == nil || value.RecoveredTransportBinding == nil || value.RecoveredTransportBinding.ResultingTransportBinding == nil {
		return RecoveredAttachAcknowledgement{}, errors.New("terminal ACK recovery carrier is incomplete")
	}
	ack, err := AttachAckFromProto(value.RecoveredAttachAckResult)
	if err != nil {
		return RecoveredAttachAcknowledgement{}, err
	}
	rebind := value.RecoveredTransportBinding
	binding := rebind.ResultingTransportBinding
	if rebind.PreviousTransportBindingFingerprint == "" || rebind.RebindReceiptFingerprint == "" {
		return RecoveredAttachAcknowledgement{}, errors.New("terminal recovered binding is incomplete")
	}
	if rebind.Disposition != protocol.AttachmentTransportRebindDisposition_ATTACHMENT_TRANSPORT_REBOUND && rebind.Disposition != protocol.AttachmentTransportRebindDisposition_ATTACHMENT_TRANSPORT_COMPATIBLE_ALREADY_REBOUND {
		return RecoveredAttachAcknowledgement{}, errors.New("terminal recovered binding disposition is unknown")
	}
	validatedBinding, err := transportBindingFromProto(binding)
	if err != nil {
		return RecoveredAttachAcknowledgement{}, err
	}
	if err := protocol.ValidateFingerprint("terminal-attachment-transport-rebind:v1", rebind, "rebind_receipt_fingerprint", rebind.RebindReceiptFingerprint); err != nil {
		return RecoveredAttachAcknowledgement{}, err
	}
	if binding.AttachmentId != ack.AttachmentID || binding.AttachmentGeneration != ack.AttachmentGeneration {
		return RecoveredAttachAcknowledgement{}, errors.New("terminal recovered binding crosses attachments")
	}
	return RecoveredAttachAcknowledgement{
		Ack: ack,
		Binding: RecoveredAttachmentTransportBinding{
			PreviousBindingFingerprint: rebind.PreviousTransportBindingFingerprint,
			ResultingBinding:           validatedBinding,
			Disposition:                rebind.Disposition,
			ReceiptFingerprint:         rebind.RebindReceiptFingerprint,
		},
	}, nil
}

func transportBindingFromProto(value *protocol.TerminalClientTransportBindingIdentity) (TransportBinding, error) {
	if value == nil || value.AttachmentId == "" || value.AttachmentGeneration == 0 || value.ConnectionId == "" || value.TransportBindingGeneration == 0 || value.BoundAtUtc == "" || value.BindingFingerprint == "" {
		return TransportBinding{}, errors.New("terminal transport binding is incomplete")
	}
	if _, err := time.Parse(time.RFC3339Nano, value.BoundAtUtc); err != nil {
		return TransportBinding{}, errors.New("terminal transport binding time is invalid")
	}
	if err := protocol.ValidateFingerprint("terminal-client-transport-binding:v1", value, "binding_fingerprint", value.BindingFingerprint); err != nil {
		return TransportBinding{}, err
	}
	return TransportBinding{
		AttachmentID: value.AttachmentId, AttachmentGeneration: value.AttachmentGeneration,
		ConnectionID: value.ConnectionId, Generation: value.TransportBindingGeneration,
		BoundAtUTC: value.BoundAtUtc, Fingerprint: value.BindingFingerprint,
	}, nil
}

func (value TransportBinding) toProto() (*protocol.TerminalClientTransportBindingIdentity, error) {
	wire := &protocol.TerminalClientTransportBindingIdentity{
		AttachmentId: value.AttachmentID, AttachmentGeneration: value.AttachmentGeneration,
		ConnectionId: value.ConnectionID, TransportBindingGeneration: value.Generation,
		BoundAtUtc: value.BoundAtUTC, BindingFingerprint: value.Fingerprint,
	}
	validated, err := transportBindingFromProto(wire)
	if err != nil || validated != value {
		if err != nil {
			return nil, err
		}
		return nil, errors.New("terminal transport binding carrier is inconsistent")
	}
	return wire, nil
}

func HelloFromProto(value *protocol.ServerHello, preparedChallengeHandleID string) (HelloNegotiationWinner, ValidatedServerHelloReceipt, error) {
	if value == nil || value.NegotiationWinner == nil || value.Receipt == nil || preparedChallengeHandleID == "" {
		return HelloNegotiationWinner{}, ValidatedServerHelloReceipt{}, errors.New("terminal Hello proof is incomplete")
	}
	winner, receipt := value.NegotiationWinner, value.Receipt
	if err := ValidateSelectedProtocol(winner.SelectedProtocol); err != nil {
		return HelloNegotiationWinner{}, ValidatedServerHelloReceipt{}, err
	}
	if err := ValidateCapabilities(winner.SelectedCapabilities); err != nil {
		return HelloNegotiationWinner{}, ValidatedServerHelloReceipt{}, err
	}
	if winner.NegotiatedLimits == nil || winner.NegotiatedLimits.MaximumFrameBytes != MaximumFrameBytes || winner.NegotiatedLimits.MaximumHistoryPageCells != MaximumHistoryPageCells || winner.NegotiatedLimits.MaximumHistoryPageDecodedBytes != MaximumHistoryPageDecodedBytes || winner.NegotiatedLimits.MaximumObservationWaitMs != MaximumObservationWaitMS || winner.NegotiatedLimits.SecretFrameMaximumBytes != SecretFrameMaximumBytes || winner.NegotiatedLimits.MaximumActiveQueueItems != MaximumActiveQueueItems || winner.NegotiatedLimits.MaximumServerControlNotifications != MaximumServerNotifications || winner.NegotiatedLimits.MaximumOperationalActivityCells != MaximumOperationalActivities || winner.NegotiatedLimits.MaximumDurableObservationBytes != MaximumDurableObservationBytes || winner.NegotiatedLimits.MaximumOperationalObservationBytes != MaximumOperationalBytes || winner.NegotiatedLimits.MaximumControlObservationBytes != MaximumControlObservationBytes || winner.NegotiatedLimits.MaximumObservationBatchBytes != MaximumObservationBatchBytes {
		return HelloNegotiationWinner{}, ValidatedServerHelloReceipt{}, errors.New("terminal negotiated limits drifted from the S1 contract")
	}
	if err := protocol.ValidateFingerprint("terminal-hello-negotiation-winner:v1", winner, "negotiation_winner_fingerprint", winner.NegotiationWinnerFingerprint); err != nil {
		return HelloNegotiationWinner{}, ValidatedServerHelloReceipt{}, err
	}
	if err := protocol.ValidateFingerprint("terminal-server-hello-receipt:v1", receipt, "hello_receipt_fingerprint", receipt.HelloReceiptFingerprint); err != nil {
		return HelloNegotiationWinner{}, ValidatedServerHelloReceipt{}, err
	}
	if len(receipt.AttachmentChallenge) != 32 || receipt.AttachmentChallengeCommitment == "" {
		return HelloNegotiationWinner{}, ValidatedServerHelloReceipt{}, errors.New("terminal attachment challenge is invalid")
	}
	return HelloNegotiationWinner{
			CandidateID: winner.HandshakeCandidateId, CandidateFingerprint: winner.HandshakeCandidateFingerprint,
			AttachmentAttemptGeneration: winner.AttachmentAttemptGeneration,
			SelectedProtocolMajor:       winner.SelectedProtocol.Major, SelectedProtocolMinor: winner.SelectedProtocol.Minor,
			SelectedSchemaFingerprint: winner.SelectedProtocol.SchemaContractFingerprint,
			SelectedCapabilities:      append([]protocol.TerminalClientCapability(nil), winner.SelectedCapabilities...),
			Limits: NegotiatedLimits{
				MaximumFrameBytes:                  winner.NegotiatedLimits.MaximumFrameBytes,
				MaximumHistoryPageCells:            winner.NegotiatedLimits.MaximumHistoryPageCells,
				MaximumHistoryPageDecodedBytes:     winner.NegotiatedLimits.MaximumHistoryPageDecodedBytes,
				MaximumObservationWaitMS:           winner.NegotiatedLimits.MaximumObservationWaitMs,
				SecretFrameMaximumBytes:            winner.NegotiatedLimits.SecretFrameMaximumBytes,
				MaximumActiveQueueItems:            winner.NegotiatedLimits.MaximumActiveQueueItems,
				MaximumServerControlNotifications:  winner.NegotiatedLimits.MaximumServerControlNotifications,
				MaximumOperationalActivityCells:    winner.NegotiatedLimits.MaximumOperationalActivityCells,
				MaximumDurableObservationBytes:     winner.NegotiatedLimits.MaximumDurableObservationBytes,
				MaximumOperationalObservationBytes: winner.NegotiatedLimits.MaximumOperationalObservationBytes,
				MaximumControlObservationBytes:     winner.NegotiatedLimits.MaximumControlObservationBytes,
				MaximumObservationBatchBytes:       winner.NegotiatedLimits.MaximumObservationBatchBytes,
			},
			CapabilityFingerprint:        winner.CapabilityContractFingerprint,
			NegotiationTranscript:        winner.NegotiationTranscriptFingerprint,
			NegotiationWinnerFingerprint: winner.NegotiationWinnerFingerprint,
		}, ValidatedServerHelloReceipt{
			RequestID: receipt.RequestId, TransportAuthAttemptID: receipt.TransportAuthAttemptId,
			CandidateID: receipt.HandshakeCandidateId, CandidateFingerprint: receipt.HandshakeCandidateFingerprint,
			NegotiationWinnerFingerprint: receipt.NegotiationWinnerFingerprint,
			CurrentConnectionID:          receipt.CurrentConnectionId, ChallengeCommitment: receipt.AttachmentChallengeCommitment,
			ReceiptFingerprint: receipt.HelloReceiptFingerprint, PreparedChallengeHandleID: preparedChallengeHandleID,
		}, nil
}

func HelloNegativeFromProto(value *protocol.HelloOutcome, requestID, authAttemptID, connectionID string, candidate HandshakeCandidate) (HelloNegativeOutcome, error) {
	if value == nil || requestID == "" || authAttemptID == "" || connectionID == "" || candidate.ID == "" || candidate.Fingerprint == "" {
		return HelloNegativeOutcome{}, errors.New("terminal negative Hello attribution is incomplete")
	}
	var kind HelloNegativeKind
	var outcomeRequestID, outcomeAuthAttemptID, outcomeConnectionID, outcomeCandidateID, outcomeCandidateFingerprint, outcomeFingerprint string
	var terminal *protocol.HandshakeCandidateTerminalReceipt
	switch branch := value.Outcome.(type) {
	case *protocol.HelloOutcome_Unavailable:
		kind = HelloNegotiationUnavailable
		if branch.Unavailable == nil {
			return HelloNegativeOutcome{}, errors.New("terminal unavailable Hello is empty")
		}
		item := branch.Unavailable
		if err := protocol.ValidateFingerprint("terminal-hello-negotiation-unavailable:v1", item, "outcome_fingerprint", item.OutcomeFingerprint); err != nil {
			return HelloNegativeOutcome{}, err
		}
		outcomeRequestID, outcomeAuthAttemptID, outcomeConnectionID = item.RequestId, item.TransportAuthAttemptId, item.CurrentConnectionId
		outcomeCandidateID, outcomeCandidateFingerprint, outcomeFingerprint, terminal = item.HandshakeCandidateId, item.HandshakeCandidateFingerprint, item.OutcomeFingerprint, item.CandidateTerminalReceipt
	case *protocol.HelloOutcome_Rejected:
		kind = HelloRejected
		if branch.Rejected == nil {
			return HelloNegativeOutcome{}, errors.New("terminal rejected Hello is empty")
		}
		item := branch.Rejected
		if err := protocol.ValidateFingerprint("terminal-hello-rejected:v1", item, "outcome_fingerprint", item.OutcomeFingerprint); err != nil {
			return HelloNegativeOutcome{}, err
		}
		outcomeRequestID, outcomeAuthAttemptID, outcomeConnectionID = item.RequestId, item.TransportAuthAttemptId, item.CurrentConnectionId
		outcomeCandidateID, outcomeCandidateFingerprint, outcomeFingerprint, terminal = item.HandshakeCandidateId, item.HandshakeCandidateFingerprint, item.OutcomeFingerprint, item.CandidateTerminalReceipt
	default:
		return HelloNegativeOutcome{}, errors.New("terminal Hello is not a negative outcome")
	}
	if terminal == nil || outcomeRequestID != requestID || outcomeAuthAttemptID != authAttemptID || outcomeConnectionID != connectionID || outcomeCandidateID != candidate.ID || outcomeCandidateFingerprint != candidate.Fingerprint || terminal.HandshakeCandidateId != candidate.ID || terminal.HandshakeCandidateFingerprint != candidate.Fingerprint || terminal.AttachmentAttemptGeneration != candidate.AttachmentAttemptGeneration || terminal.CandidateRegistryRevision == 0 || terminal.TerminalReceiptFingerprint == "" {
		return HelloNegativeOutcome{}, errors.New("terminal negative Hello authority join is invalid")
	}
	if err := protocol.ValidateFingerprint("terminal-handshake-candidate-terminal:v1", terminal, "terminal_receipt_fingerprint", terminal.TerminalReceiptFingerprint); err != nil {
		return HelloNegativeOutcome{}, err
	}
	hasPrior := terminal.PriorNegotiationWinnerFingerprint != nil
	prior := ""
	if hasPrior {
		prior = *terminal.PriorNegotiationWinnerFingerprint
	}
	if err := validateHelloTerminalMatrix(kind, terminal, hasPrior); err != nil {
		return HelloNegativeOutcome{}, err
	}
	validated := HandshakeCandidateTerminalReceipt{
		CandidateID: terminal.HandshakeCandidateId, CandidateFingerprint: terminal.HandshakeCandidateFingerprint,
		AttachmentAttemptGeneration: terminal.AttachmentAttemptGeneration, TerminalDisposition: terminal.TerminalDisposition,
		TerminalReason: terminal.TerminalReason, RequiredClientDisposition: terminal.RequiredClientDisposition,
		PriorNegotiationWinnerFingerprint: prior, HasPriorNegotiationWinner: hasPrior,
		CandidateRegistryRevision: terminal.CandidateRegistryRevision, TerminalReceiptFingerprint: terminal.TerminalReceiptFingerprint,
	}
	return HelloNegativeOutcome{Kind: kind, RequestID: outcomeRequestID, TransportAuthAttemptID: outcomeAuthAttemptID, CurrentConnectionID: outcomeConnectionID, CandidateID: outcomeCandidateID, CandidateFingerprint: outcomeCandidateFingerprint, TerminalReceipt: validated, OutcomeFingerprint: outcomeFingerprint}, nil
}

func validateHelloTerminalMatrix(kind HelloNegativeKind, terminal *protocol.HandshakeCandidateTerminalReceipt, hasPrior bool) error {
	if terminal.TerminalDisposition == protocol.HandshakeCandidateTerminalDisposition_HANDSHAKE_CANDIDATE_TERMINAL_DISPOSITION_UNSPECIFIED || terminal.TerminalReason == protocol.HelloCandidateTerminalReason_HELLO_CANDIDATE_TERMINAL_REASON_UNSPECIFIED || terminal.RequiredClientDisposition == protocol.HelloCandidateClientDisposition_HELLO_CANDIDATE_CLIENT_DISPOSITION_UNSPECIFIED {
		return errors.New("terminal negative Hello vocabulary is unknown")
	}
	if kind == HelloNegotiationUnavailable {
		validReason := terminal.TerminalReason == protocol.HelloCandidateTerminalReason_FROZEN_WINNER_BINDING_MISSING || terminal.TerminalReason == protocol.HelloCandidateTerminalReason_FROZEN_WINNER_CONTRACT_UNSUPPORTED || terminal.TerminalReason == protocol.HelloCandidateTerminalReason_FROZEN_WINNER_RUNTIME_INCOMPATIBLE
		if terminal.TerminalDisposition != protocol.HandshakeCandidateTerminalDisposition_NEGOTIATION_WINNER_UNAVAILABLE || !validReason || terminal.RequiredClientDisposition != protocol.HelloCandidateClientDisposition_PARENT_RELAUNCH_NEW_CANDIDATE || !hasPrior {
			return errors.New("terminal unavailable Hello matrix is invalid")
		}
		return nil
	}
	if terminal.TerminalDisposition != protocol.HandshakeCandidateTerminalDisposition_HELLO_REJECTED || hasPrior {
		return errors.New("terminal rejected Hello matrix is invalid")
	}
	if terminal.TerminalReason == protocol.HelloCandidateTerminalReason_CANDIDATE_EXPIRED {
		if terminal.RequiredClientDisposition != protocol.HelloCandidateClientDisposition_PARENT_RELAUNCH_NEW_CANDIDATE {
			return errors.New("expired Hello candidate requires relaunch")
		}
		return nil
	}
	validFatalReason := terminal.TerminalReason == protocol.HelloCandidateTerminalReason_PROTOCOL_RANGE_UNSUPPORTED || terminal.TerminalReason == protocol.HelloCandidateTerminalReason_SCHEMA_CONTRACT_UNSUPPORTED || terminal.TerminalReason == protocol.HelloCandidateTerminalReason_MISSING_REQUIRED_CAPABILITY || terminal.TerminalReason == protocol.HelloCandidateTerminalReason_SERVER_NEGOTIATION_POLICY_REJECTED
	if !validFatalReason || terminal.RequiredClientDisposition != protocol.HelloCandidateClientDisposition_FATAL_COMPATIBILITY {
		return errors.New("terminal fatal Hello rejection matrix is invalid")
	}
	return nil
}

func AttachFromProto(value *protocol.AttachResultReceipt, clientInstanceID string) (Attachment, AttachReceipt, error) {
	if value == nil || value.AttachSemanticWinner == nil || value.AttachSemanticWinner.Attachment == nil || value.CurrentTransportBinding == nil {
		return Attachment{}, AttachReceipt{}, errors.New("terminal attach proof is incomplete")
	}
	semantic, identity, binding := value.AttachSemanticWinner, value.AttachSemanticWinner.Attachment, value.CurrentTransportBinding
	if err := protocol.ValidateFingerprint("terminal-attachment-identity:v2", identity, "identity_fingerprint", identity.IdentityFingerprint); err != nil {
		return Attachment{}, AttachReceipt{}, err
	}
	validatedBinding, err := transportBindingFromProto(binding)
	if err != nil {
		return Attachment{}, AttachReceipt{}, err
	}
	if err := protocol.ValidateFingerprint("terminal-attach-semantic-winner:v1", semantic, "semantic_winner_fingerprint", semantic.SemanticWinnerFingerprint); err != nil {
		return Attachment{}, AttachReceipt{}, err
	}
	if err := protocol.ValidateFingerprint("terminal-attach-result-receipt:v1", value, "receipt_fingerprint", value.ReceiptFingerprint); err != nil {
		return Attachment{}, AttachReceipt{}, err
	}
	issued, err := time.Parse(time.RFC3339Nano, identity.IssuedAtUtc)
	if err != nil {
		return Attachment{}, AttachReceipt{}, errors.New("terminal attachment issue time is invalid")
	}
	expires, err := time.Parse(time.RFC3339Nano, identity.ExpiresAtUtc)
	if err != nil || !issued.Before(expires) {
		return Attachment{}, AttachReceipt{}, errors.New("terminal attachment expiry is invalid")
	}
	if semantic.HeartbeatPolicy == nil || semantic.HeartbeatPolicy.IntervalMs == 0 || semantic.HeartbeatPolicy.MaximumMissedCount == 0 {
		return Attachment{}, AttachReceipt{}, errors.New("terminal heartbeat policy is invalid")
	}
	if binding.AttachmentId != identity.AttachmentId || binding.AttachmentGeneration != identity.AttachmentGeneration || identity.ClientInstanceId != clientInstanceID {
		return Attachment{}, AttachReceipt{}, errors.New("terminal attach identity join is invalid")
	}
	if semantic.ControllerDisposition == protocol.ControllerDisposition_CONTROLLER_DISPOSITION_UNSPECIFIED || semantic.BootstrapRequirement != protocol.BootstrapRequirement_PROJECTION_AND_OPERATIONAL_SNAPSHOT_REQUIRED {
		return Attachment{}, AttachReceipt{}, errors.New("terminal attach vocabulary is incompatible")
	}
	previous := ""
	if value.PreviousTransportBindingFingerprint != nil {
		previous = *value.PreviousTransportBindingFingerprint
	}
	return Attachment{
			ClientInstanceID: identity.ClientInstanceId, AttachmentAttemptGeneration: semantic.AttachmentAttemptGeneration,
			ConnectionID: binding.ConnectionId, BindingGeneration: binding.TransportBindingGeneration,
			BindingFingerprint: binding.BindingFingerprint, ID: identity.AttachmentId,
			RuntimeSessionID: identity.RuntimeSessionId, Generation: identity.AttachmentGeneration,
			Role: identity.Role, ControllerGeneration: identity.ControllerGeneration,
			IssuedAt: issued, ExpiresAt: expires, IdentityFingerprint: identity.IdentityFingerprint,
			SemanticWinnerFingerprint: semantic.SemanticWinnerFingerprint, CurrentReceiptFingerprint: value.ReceiptFingerprint,
			ControllerDisposition: semantic.ControllerDisposition, BootstrapRequirement: semantic.BootstrapRequirement,
			Heartbeat: HeartbeatPolicy{Interval: time.Duration(semantic.HeartbeatPolicy.IntervalMs) * time.Millisecond, Grace: time.Duration(semantic.HeartbeatPolicy.GraceMs) * time.Millisecond, MaximumMissedCount: semantic.HeartbeatPolicy.MaximumMissedCount},
		}, AttachReceipt{
			RequestID: value.RequestId, TransportAuthAttemptID: value.TransportAuthAttemptId,
			CandidateID: value.HandshakeCandidateId, CandidateFingerprint: value.HandshakeCandidateFingerprint,
			SemanticWinnerFingerprint: semantic.SemanticWinnerFingerprint, CurrentBinding: validatedBinding,
			PreviousBindingFingerprint: previous, HasPreviousBinding: value.PreviousTransportBindingFingerprint != nil,
			Disposition: value.Disposition, ReceiptFingerprint: value.ReceiptFingerprint,
		}, nil
}

func AttachAckFromProto(value *protocol.AttachAckResult) (ValidatedAttachAckResult, error) {
	if value == nil || value.RequestId == "" || value.AttachmentId == "" || value.AttachmentGeneration == 0 || value.SemanticWinnerFingerprint == "" || value.AcknowledgedTransportBindingFingerprint == "" || value.AckResultFingerprint == "" {
		return ValidatedAttachAckResult{}, errors.New("terminal attach ACK proof is incomplete")
	}
	if value.Disposition != protocol.AttachAckDisposition_ATTACH_ACKNOWLEDGED && value.Disposition != protocol.AttachAckDisposition_ATTACH_COMPATIBLE_ALREADY_ACKNOWLEDGED {
		return ValidatedAttachAckResult{}, errors.New("terminal attach ACK disposition is unknown")
	}
	if err := protocol.ValidateFingerprint("terminal-attach-ack-result:v1", value, "ack_result_fingerprint", value.AckResultFingerprint); err != nil {
		return ValidatedAttachAckResult{}, err
	}
	return ValidatedAttachAckResult{RequestID: value.RequestId, AttachmentID: value.AttachmentId, AttachmentGeneration: value.AttachmentGeneration, SemanticWinnerFingerprint: value.SemanticWinnerFingerprint, AcknowledgedBindingFingerprint: value.AcknowledgedTransportBindingFingerprint, Disposition: value.Disposition, RetiredCredentialID: value.RetiredCredentialId, ResultFingerprint: value.AckResultFingerprint}, nil
}

func PrepareHeartbeatRequest(requestID string, attachment Attachment, receipt AttachReceipt, heartbeatGeneration, previousAcceptedGeneration uint64) (PreparedHeartbeatRequest, error) {
	if requestID == "" || attachment.ID == "" || attachment.Generation == 0 || attachment.RuntimeSessionID == "" || attachment.IdentityFingerprint == "" || attachment.SemanticWinnerFingerprint == "" || receipt.SemanticWinnerFingerprint != attachment.SemanticWinnerFingerprint || heartbeatGeneration == 0 || heartbeatGeneration != previousAcceptedGeneration+1 {
		return PreparedHeartbeatRequest{}, errors.New("terminal heartbeat preparation authority is invalid")
	}
	if receipt.CurrentBinding.AttachmentID != attachment.ID || receipt.CurrentBinding.AttachmentGeneration != attachment.Generation || receipt.CurrentBinding.ConnectionID != attachment.ConnectionID || receipt.CurrentBinding.Generation != attachment.BindingGeneration || receipt.CurrentBinding.Fingerprint != attachment.BindingFingerprint {
		return PreparedHeartbeatRequest{}, errors.New("terminal heartbeat transport binding is stale")
	}
	binding, err := receipt.CurrentBinding.toProto()
	if err != nil {
		return PreparedHeartbeatRequest{}, err
	}
	candidateFingerprint, err := protocol.CanonicalJSONFingerprint(
		"terminal-heartbeat-candidate:v1",
		map[string]any{
			"runtime_session_id":              attachment.RuntimeSessionID,
			"attachment_identity_fingerprint": attachment.IdentityFingerprint,
			"semantic_winner_fingerprint":     attachment.SemanticWinnerFingerprint,
			"heartbeat_generation":            heartbeatGeneration,
			"previous_accepted_generation":    previousAcceptedGeneration,
		},
	)
	if err != nil {
		return PreparedHeartbeatRequest{}, err
	}
	request := &protocol.HeartbeatRequest{
		RequestId: requestID, RuntimeSessionId: attachment.RuntimeSessionID,
		AttachmentId: attachment.ID, AttachmentGeneration: attachment.Generation,
		AttachmentIdentityFingerprint:   attachment.IdentityFingerprint,
		AttachSemanticWinnerFingerprint: attachment.SemanticWinnerFingerprint,
		CurrentTransportBinding:         binding, HeartbeatGeneration: heartbeatGeneration,
		PreviousAcceptedHeartbeatGeneration: previousAcceptedGeneration,
		HeartbeatCandidateFingerprint:       candidateFingerprint,
	}
	if _, err := protocol.InstallFingerprint("terminal-heartbeat-request:v1", request, "request_fingerprint"); err != nil {
		return PreparedHeartbeatRequest{}, err
	}
	return PreparedHeartbeatRequest{
		RequestID: request.RequestId, RuntimeSessionID: request.RuntimeSessionId,
		AttachmentID: request.AttachmentId, AttachmentGeneration: request.AttachmentGeneration,
		AttachmentIdentityFingerprint: request.AttachmentIdentityFingerprint,
		SemanticWinnerFingerprint:     request.AttachSemanticWinnerFingerprint,
		CurrentBinding:                receipt.CurrentBinding, HeartbeatGeneration: request.HeartbeatGeneration,
		PreviousAcceptedGeneration: request.PreviousAcceptedHeartbeatGeneration,
		CandidateFingerprint:       request.HeartbeatCandidateFingerprint,
		RequestFingerprint:         request.RequestFingerprint,
	}, nil
}

func (value PreparedHeartbeatRequest) ToProto() (*protocol.HeartbeatRequest, error) {
	binding, err := value.CurrentBinding.toProto()
	if err != nil {
		return nil, err
	}
	request := &protocol.HeartbeatRequest{
		RequestId: value.RequestID, RuntimeSessionId: value.RuntimeSessionID,
		AttachmentId: value.AttachmentID, AttachmentGeneration: value.AttachmentGeneration,
		AttachmentIdentityFingerprint:   value.AttachmentIdentityFingerprint,
		AttachSemanticWinnerFingerprint: value.SemanticWinnerFingerprint,
		CurrentTransportBinding:         binding, HeartbeatGeneration: value.HeartbeatGeneration,
		PreviousAcceptedHeartbeatGeneration: value.PreviousAcceptedGeneration,
		HeartbeatCandidateFingerprint:       value.CandidateFingerprint,
		RequestFingerprint:                  value.RequestFingerprint,
	}
	if err := protocol.ValidateFingerprint("terminal-heartbeat-request:v1", request, "request_fingerprint", request.RequestFingerprint); err != nil {
		return nil, err
	}
	return request, nil
}

func PrepareOperationalSnapshotRequest(requestID string, attachment Attachment, receipt AttachReceipt, requestedAfterGeneration, requestedAfterCursor uint64) (PreparedOperationalSnapshotRequest, error) {
	if requestID == "" || attachment.ID == "" || attachment.Generation == 0 || attachment.RuntimeSessionID == "" || attachment.IdentityFingerprint == "" || (requestedAfterGeneration == 0 && requestedAfterCursor != 0) {
		return PreparedOperationalSnapshotRequest{}, errors.New("terminal operational snapshot preparation authority is invalid")
	}
	if receipt.SemanticWinnerFingerprint != attachment.SemanticWinnerFingerprint || receipt.CurrentBinding.AttachmentID != attachment.ID || receipt.CurrentBinding.AttachmentGeneration != attachment.Generation || receipt.CurrentBinding.ConnectionID != attachment.ConnectionID || receipt.CurrentBinding.Generation != attachment.BindingGeneration || receipt.CurrentBinding.Fingerprint != attachment.BindingFingerprint {
		return PreparedOperationalSnapshotRequest{}, errors.New("terminal operational snapshot transport binding is stale")
	}
	binding, err := receipt.CurrentBinding.toProto()
	if err != nil {
		return PreparedOperationalSnapshotRequest{}, err
	}
	request := &protocol.OperationalSnapshotRequest{
		RequestId: requestID, RuntimeSessionId: attachment.RuntimeSessionID,
		AttachmentId: attachment.ID, AttachmentGeneration: attachment.Generation,
		AttachmentIdentityFingerprint:       attachment.IdentityFingerprint,
		CurrentTransportBinding:             binding,
		RequestedAfterOperationalGeneration: requestedAfterGeneration,
		RequestedAfterOperationalCursor:     requestedAfterCursor,
	}
	if _, err := protocol.InstallFingerprint("terminal-operational-snapshot-request:v1", request, "request_fingerprint"); err != nil {
		return PreparedOperationalSnapshotRequest{}, err
	}
	return PreparedOperationalSnapshotRequest{
		RequestID: request.RequestId, RuntimeSessionID: request.RuntimeSessionId,
		AttachmentID: request.AttachmentId, AttachmentGeneration: request.AttachmentGeneration,
		AttachmentIdentityFingerprint: request.AttachmentIdentityFingerprint,
		CurrentBinding:                receipt.CurrentBinding,
		RequestedAfterGeneration:      request.RequestedAfterOperationalGeneration,
		RequestedAfterCursor:          request.RequestedAfterOperationalCursor,
		RequestFingerprint:            request.RequestFingerprint,
	}, nil
}

func (value PreparedOperationalSnapshotRequest) ToProto() (*protocol.OperationalSnapshotRequest, error) {
	binding, err := value.CurrentBinding.toProto()
	if err != nil {
		return nil, err
	}
	request := &protocol.OperationalSnapshotRequest{
		RequestId: value.RequestID, RuntimeSessionId: value.RuntimeSessionID,
		AttachmentId: value.AttachmentID, AttachmentGeneration: value.AttachmentGeneration,
		AttachmentIdentityFingerprint:       value.AttachmentIdentityFingerprint,
		CurrentTransportBinding:             binding,
		RequestedAfterOperationalGeneration: value.RequestedAfterGeneration,
		RequestedAfterOperationalCursor:     value.RequestedAfterCursor,
		RequestFingerprint:                  value.RequestFingerprint,
	}
	if err := protocol.ValidateFingerprint("terminal-operational-snapshot-request:v1", request, "request_fingerprint", request.RequestFingerprint); err != nil {
		return nil, err
	}
	return request, nil
}

func HeartbeatAcceptedFromProto(value *protocol.HeartbeatAcceptedReceipt) (ValidatedHeartbeatAcceptedReceipt, error) {
	if value == nil || value.ReceiptFingerprint == "" || value.LivenessDisposition == protocol.HeartbeatLivenessDisposition_HEARTBEAT_LIVENESS_DISPOSITION_UNSPECIFIED {
		return ValidatedHeartbeatAcceptedReceipt{}, errors.New("terminal heartbeat accepted proof is incomplete")
	}
	if err := protocol.ValidateFingerprint("terminal-heartbeat-accepted-receipt:v1", value, "receipt_fingerprint", value.ReceiptFingerprint); err != nil {
		return ValidatedHeartbeatAcceptedReceipt{}, err
	}
	expires, err := time.Parse(time.RFC3339Nano, value.ResultingAttachmentLeaseExpiresAt)
	if err != nil {
		return ValidatedHeartbeatAcceptedReceipt{}, errors.New("terminal heartbeat expiry is invalid")
	}
	return ValidatedHeartbeatAcceptedReceipt{RequestID: value.RequestId, RuntimeSessionID: value.RuntimeSessionId, AttachmentID: value.AttachmentId, AttachmentGeneration: value.AttachmentGeneration, AttachmentIdentityFingerprint: value.AttachmentIdentityFingerprint, SemanticWinnerFingerprint: value.AttachSemanticWinnerFingerprint, AcknowledgedBindingFingerprint: value.AcknowledgedTransportBindingFingerprint, HeartbeatGeneration: value.HeartbeatGeneration, PreviousAcceptedGeneration: value.PreviousAcceptedHeartbeatGeneration, CandidateFingerprint: value.HeartbeatCandidateFingerprint, LeaseExpiresAt: expires, LivenessDisposition: value.LivenessDisposition, SemanticResultFingerprint: value.HeartbeatSemanticResultFingerprint, ReceiptFingerprint: value.ReceiptFingerprint}, nil
}

func HeartbeatRejectedFromProto(value *protocol.HeartbeatRejectedReceipt) (ValidatedHeartbeatRejectedReceipt, error) {
	if value == nil || value.ReceiptFingerprint == "" || value.RejectionReason == protocol.HeartbeatRejectedReason_HEARTBEAT_REJECTED_REASON_UNSPECIFIED {
		return ValidatedHeartbeatRejectedReceipt{}, errors.New("terminal heartbeat rejection proof is incomplete")
	}
	if err := protocol.ValidateFingerprint("terminal-heartbeat-rejected-receipt:v1", value, "receipt_fingerprint", value.ReceiptFingerprint); err != nil {
		return ValidatedHeartbeatRejectedReceipt{}, err
	}
	return ValidatedHeartbeatRejectedReceipt{RequestID: value.RequestId, RuntimeSessionID: value.RuntimeSessionId, AttachmentID: value.AttachmentId, AttachmentGeneration: value.AttachmentGeneration, AttachmentIdentityFingerprint: value.AttachmentIdentityFingerprint, SemanticWinnerFingerprint: value.AttachSemanticWinnerFingerprint, SubmittedBindingFingerprint: value.SubmittedTransportBindingFingerprint, HeartbeatGeneration: value.HeartbeatGeneration, PreviousAcceptedGeneration: value.PreviousAcceptedHeartbeatGeneration, CandidateFingerprint: value.HeartbeatCandidateFingerprint, Reason: value.RejectionReason, SemanticResultFingerprint: value.HeartbeatSemanticResultFingerprint, ReceiptFingerprint: value.ReceiptFingerprint}, nil
}

func DurableSnapshotFromWire(frame *protocol.ProjectionSnapshotFrame) (DurableSnapshot, error) {
	if frame == nil || frame.RequestId == "" || frame.HostSessionId == "" || frame.RuntimeSessionId == "" || frame.SnapshotFingerprint == "" {
		return DurableSnapshot{}, errors.New("durable snapshot identity is incomplete")
	}
	if frame.ActiveHead == nil || frame.ActiveHead.ActiveHeadFingerprint == "" || frame.ControlProjectionSnapshot == nil || frame.ControlProjectionSnapshot.View == nil || frame.ControlProjectionSnapshot.Cursor == nil {
		return DurableSnapshot{}, errors.New("durable snapshot authority is incomplete")
	}
	if err := validateDurableSnapshotSpine(frame); err != nil {
		return DurableSnapshot{}, err
	}
	control, err := controlProjectionFromWire(frame.RuntimeSessionId, frame.ControlProjectionSnapshot)
	if err != nil {
		return DurableSnapshot{}, err
	}
	cells := make([]HistoryCell, 0, len(frame.OrderedResidentEntries))
	seen := map[string]bool{}
	for _, ranked := range frame.OrderedResidentEntries {
		if ranked == nil || ranked.Entry == nil || ranked.Entry.PlacementKey == nil || ranked.Entry.PlacementKey.RelativePositionKind == protocol.PresentationRelativePositionKind_PRESENTATION_RELATIVE_POSITION_KIND_UNSPECIFIED || ranked.Entry.HistoryEntryId == "" || ranked.Entry.EntryFingerprint == "" || seen[ranked.Entry.HistoryEntryId] {
			return DurableSnapshot{}, errors.New("resident history entry identity is invalid")
		}
		seen[ranked.Entry.HistoryEntryId] = true
		kind, revision, text, fingerprint, err := PublicText(ranked.Entry.DurableHistoryCell)
		if err != nil {
			return DurableSnapshot{}, err
		}
		cells = append(cells, HistoryCell{ID: ranked.Entry.HistoryEntryId, Revision: revision, Kind: kind, PublicText: text, Fingerprint: fingerprint})
	}
	return DurableSnapshot{RequestID: frame.RequestId, HostSessionID: frame.HostSessionId, RuntimeSessionID: frame.RuntimeSessionId, AuthorityHighWater: frame.AuthorityHighWater, ProjectionRevision: frame.ProjectionRevision, ActiveHeadFingerprint: frame.ActiveHead.ActiveHeadFingerprint, Control: control, Cells: cells, SnapshotFingerprint: frame.SnapshotFingerprint}, nil
}

func validateDurableSnapshotSpine(frame *protocol.ProjectionSnapshotFrame) error {
	head := frame.ActiveHead
	root := head.GetConfirmedRootIdentity()
	pair := frame.LatestRootCursorPair
	if root == nil || pair == nil || pair.RootIdentity == nil || head.CapacityState == nil || head.CapacityState.State == nil {
		return errors.New("durable snapshot spine is incomplete")
	}
	if frame.RuntimeSessionId != head.RuntimeSessionId || frame.RuntimeSessionId != root.RuntimeSessionId || frame.ProjectionContractFingerprint != root.HistoryProjectionContractFingerprint || frame.AuthorityHighWater != head.ThroughAuthoritySequence || head.TailFromSequenceExclusive != root.ThroughAuthoritySequence || head.ResultingResidentEntryCount != uint64(len(frame.OrderedResidentEntries)) || !proto.Equal(root, pair.RootIdentity) || pair.CursorPairFingerprint == "" {
		return errors.New("durable snapshot head/root join is invalid")
	}
	for _, cursor := range []*protocol.PresentationHistoryCursor{pair.BeforeCursor, pair.AfterCursor} {
		if cursor == nil {
			continue
		}
		hasEntry, hasPlacement := cursor.AnchorHistoryEntryId != nil, cursor.AnchorPlacementKey != nil
		if cursor.RuntimeSessionId != frame.RuntimeSessionId || cursor.RootIdentity == nil || !proto.Equal(cursor.RootIdentity, root) || hasEntry != hasPlacement || cursor.CursorFingerprint == "" {
			return errors.New("durable snapshot root cursor join is invalid")
		}
	}
	var previousRank uint64
	for index, ranked := range frame.OrderedResidentEntries {
		if ranked == nil || ranked.Entry == nil || ranked.RankBasis == nil || ranked.RankBasis.Basis == nil || ranked.Entry.RuntimeSessionId != frame.RuntimeSessionId || ranked.RankedViewFingerprint == "" || (index > 0 && ranked.RootLocalDisplayRank <= previousRank) {
			return errors.New("durable snapshot ranked entry spine is invalid")
		}
		previousRank = ranked.RootLocalDisplayRank
		switch basis := ranked.RankBasis.Basis.(type) {
		case *protocol.HistoryRankBasis_ConfirmedRoot:
			if basis.ConfirmedRoot == nil || basis.ConfirmedRoot.HistoryRootIdentityFingerprint != root.RootIdentityFingerprint || basis.ConfirmedRoot.RankBasisFingerprint == "" {
				return errors.New("durable snapshot confirmed-root rank basis is stale")
			}
		case *protocol.HistoryRankBasis_ActiveHead:
			if basis.ActiveHead == nil || basis.ActiveHead.HistoryActiveHeadFingerprint != head.ActiveHeadFingerprint || basis.ActiveHead.ThroughAuthoritySequence != head.ThroughAuthoritySequence || basis.ActiveHead.RankBasisFingerprint == "" {
				return errors.New("durable snapshot active-head rank basis is stale")
			}
		default:
			return errors.New("durable snapshot rank basis is unknown")
		}
	}
	return nil
}

func controlProjectionFromWire(runtimeSessionID string, snapshot *protocol.TerminalControlProjectionSnapshot) (ControlProjection, error) {
	view, cursor := snapshot.View, snapshot.Cursor
	if view.RuntimeSessionId != runtimeSessionID || view.ControlViewFingerprint == "" || snapshot.SnapshotFingerprint == "" || cursor.ControlGeneration == 0 || cursor.ControlRevision == 0 || cursor.CursorFingerprint == "" || cursor.ControlProjectionFingerprint != view.ControlViewFingerprint || cursor.RegistryContractFingerprint != ControlRegistryContractFingerprint || cursor.TransitionPrefixAccumulator == "" {
		return ControlProjection{}, errors.New("control projection snapshot join is invalid")
	}
	if view.SessionLifecycle == nil || view.SessionLifecycle.SourceVersion == nil || view.RunControl == nil || view.RunControl.SourceVersion == nil || view.PendingInteraction == nil || view.PendingInteraction.SourceVersion == nil || view.PromptQueue == nil || view.PromptQueue.SourceVersion == nil || view.PromptQueue.Projection == nil || view.ServerNotifications == nil || view.ServerNotifications.SourceVersion == nil {
		return ControlProjection{}, errors.New("control projection section is missing")
	}
	sections := []*protocol.TerminalControlSectionSourceVersion{view.SessionLifecycle.SourceVersion, view.RunControl.SourceVersion, view.PendingInteraction.SourceVersion, view.PromptQueue.SourceVersion, view.ServerNotifications.SourceVersion}
	for index, section := range sections {
		if section.SectionKind != protocol.TerminalControlSectionKind(index+1) || section.SourceOwnerId == "" || section.SourceOwnerGeneration == 0 || section.SourceOwnerRevision == 0 || section.SourceVersionFingerprint == "" || section.SourceViewFingerprint == "" {
			return ControlProjection{}, errors.New("control projection source version is invalid")
		}
	}
	sectionViews := []string{view.SessionLifecycle.ViewFingerprint, view.RunControl.ViewFingerprint, view.PendingInteraction.ViewFingerprint, view.PromptQueue.ViewFingerprint, view.ServerNotifications.ViewFingerprint}
	for index, section := range sections {
		if section.SourceViewFingerprint != sectionViews[index] {
			return ControlProjection{}, errors.New("control projection section/source join is invalid")
		}
	}
	if view.SessionLifecycle.Lifecycle == protocol.TerminalSessionLifecycleState_TERMINAL_SESSION_LIFECYCLE_STATE_UNSPECIFIED || view.PromptQueue.Projection.ProjectionFingerprint != view.PromptQueue.ViewFingerprint {
		return ControlProjection{}, errors.New("control projection section vocabulary is invalid")
	}
	queue, err := queueProjectionFromWire(view.PromptQueue.Projection)
	if err != nil {
		return ControlProjection{}, err
	}
	if interaction := view.PendingInteraction.Interaction; interaction != nil {
		if err := validatePendingInteractionPublicText(interaction); err != nil {
			return ControlProjection{}, err
		}
		if mcp := interaction.GetMcpInput(); mcp != nil {
			for _, request := range mcp.Requests {
				if request == nil || request.RequestKey == "" || request.Mode == protocol.McpInputMode_MCP_INPUT_MODE_UNSPECIFIED {
					return ControlProjection{}, errors.New("MCP interaction vocabulary is unknown")
				}
			}
		}
	}
	notifications := view.ServerNotifications
	if notifications.NotificationCount != uint32(len(notifications.OrderedNotifications)) || notifications.NotificationCount > MaximumServerNotifications || notifications.NotificationAccumulator == "" || notifications.ViewFingerprint == "" {
		return ControlProjection{}, errors.New("server notification projection bound is invalid")
	}
	notificationValues := make([]ServerNotification, 0, len(notifications.OrderedNotifications))
	lastOrdinal := uint64(0)
	seenNotifications := map[string]bool{}
	for _, item := range notifications.OrderedNotifications {
		if item == nil || item.NotificationId == "" || item.NotificationOrdinal == 0 || item.NotificationOrdinal <= lastOrdinal || item.Kind == protocol.ServerNotificationKind_SERVER_NOTIFICATION_KIND_UNSPECIFIED || item.NotificationFingerprint == "" || seenNotifications[item.NotificationId] || !publictext.IsSafe(item.PublicText) {
			return ControlProjection{}, errors.New("server notification projection is invalid")
		}
		seenNotifications[item.NotificationId], lastOrdinal = true, item.NotificationOrdinal
		notificationValues = append(notificationValues, ServerNotification{ID: item.NotificationId, Ordinal: item.NotificationOrdinal, Kind: item.Kind, PublicText: item.PublicText, Fingerprint: item.NotificationFingerprint})
	}
	activeRun := ""
	if view.RunControl.ActiveRunId != nil {
		activeRun = *view.RunControl.ActiveRunId
	}
	pendingID := ""
	pendingViewFingerprint := view.PendingInteraction.SourceVersion.SourceViewFingerprint
	if interaction := view.PendingInteraction.Interaction; interaction != nil {
		switch item := interaction.Interaction.(type) {
		case *protocol.PendingInteraction_Approval:
			pendingID, pendingViewFingerprint = item.Approval.InteractionId, item.Approval.ViewFingerprint
		case *protocol.PendingInteraction_PlanQuestion:
			pendingID, pendingViewFingerprint = item.PlanQuestion.InteractionId, item.PlanQuestion.ViewFingerprint
		case *protocol.PendingInteraction_PlanExit:
			pendingID, pendingViewFingerprint = item.PlanExit.InteractionId, item.PlanExit.ViewFingerprint
		case *protocol.PendingInteraction_McpInput:
			pendingID, pendingViewFingerprint = item.McpInput.InteractionId, item.McpInput.ViewFingerprint
		default:
			return ControlProjection{}, errors.New("pending interaction branch is unknown")
		}
		if pendingID == "" || pendingViewFingerprint == "" {
			return ControlProjection{}, errors.New("pending interaction identity is incomplete")
		}
	}
	return ControlProjection{RuntimeSessionID: runtimeSessionID, Generation: cursor.ControlGeneration, Revision: cursor.ControlRevision, ProjectionFingerprint: cursor.ControlProjectionFingerprint, TransitionAccumulator: cursor.TransitionPrefixAccumulator, RegistryFingerprint: cursor.RegistryContractFingerprint, CursorFingerprint: cursor.CursorFingerprint, SnapshotFingerprint: snapshot.SnapshotFingerprint, ViewFingerprint: view.ControlViewFingerprint, SessionLifecycle: view.SessionLifecycle.Lifecycle, ActiveRunID: activeRun, PendingInteraction: view.PendingInteraction.Interaction != nil, PendingInteractionID: pendingID, PendingInteractionGeneration: view.PendingInteraction.SourceVersion.SourceOwnerGeneration, PendingInteractionViewFingerprint: pendingViewFingerprint, QueueHeadFingerprint: queue.headFingerprint, QueueViewFingerprint: view.PromptQueue.Projection.ProjectionFingerprint, QueueAccountRevision: view.PromptQueue.Projection.QueueAccountRevision, QueueAccumulator: view.PromptQueue.Projection.ActiveItemAccumulator, QueueItems: queue.items, NotificationAccumulator: notifications.NotificationAccumulator, ServerNotifications: notificationValues}, nil
}

func validatePendingInteractionPublicText(value *protocol.PendingInteraction) error {
	switch item := value.Interaction.(type) {
	case *protocol.PendingInteraction_Approval:
		if item.Approval == nil {
			return errors.New("approval interaction is empty")
		}
		for _, tool := range item.Approval.ToolCalls {
			if tool == nil || !publictext.IsSafe(tool.ToolName) {
				return errors.New("approval interaction contains unsafe public text")
			}
		}
	case *protocol.PendingInteraction_PlanQuestion:
		if item.PlanQuestion == nil || !publictext.IsSafe(item.PlanQuestion.Question) {
			return errors.New("plan question contains unsafe public text")
		}
		for _, option := range item.PlanQuestion.Options {
			if option == nil || !publictext.IsSafe(option.Label) || !publictext.IsSafe(option.Description) {
				return errors.New("plan option contains unsafe public text")
			}
		}
	case *protocol.PendingInteraction_PlanExit:
		if item.PlanExit == nil || !publictext.IsSafe(item.PlanExit.Summary) {
			return errors.New("plan exit contains unsafe public text")
		}
	case *protocol.PendingInteraction_McpInput:
		if item.McpInput == nil || !publictext.IsSafe(item.McpInput.ToolName) {
			return errors.New("MCP interaction contains unsafe public text")
		}
		for _, request := range item.McpInput.Requests {
			if request == nil || !publictext.IsSafe(request.PublicPrompt) {
				return errors.New("MCP request contains unsafe public text")
			}
		}
	default:
		return errors.New("pending interaction branch is unknown")
	}
	return nil
}

type queueProjection struct {
	headFingerprint string
	items           []QueueItem
}

func queueProjectionFromWire(value *protocol.PromptQueueClientProjection) (queueProjection, error) {
	if value.ActiveItemCount != uint32(len(value.OrderedActiveItems)) || value.ActiveItemCount > MaximumActiveQueueItems || value.ActiveItemAccumulator == "" || value.ProjectionFingerprint == "" || value.QueueHead == nil || value.ProjectionContractId != "terminal-active-prompt-queue-projection" || value.ProjectionContractVersion != 1 || value.ProjectionContractFingerprint != ActiveQueueContractFingerprint {
		return queueProjection{}, errors.New("active queue projection bound is invalid")
	}
	headFingerprint := ""
	switch head := value.QueueHead.Head.(type) {
	case *protocol.PromptQueueProjectionHead_EmptyGenesis:
		if head.EmptyGenesis == nil || head.EmptyGenesis.CheckpointGeneration != 0 || head.EmptyGenesis.CheckpointTransitionCount != 0 || head.EmptyGenesis.BoundedTailCount != 0 || value.ActiveItemCount != 0 || head.EmptyGenesis.HeadReceiptFingerprint == "" || head.EmptyGenesis.EmptyHeadFingerprint == "" {
			return queueProjection{}, errors.New("empty queue genesis proof is invalid")
		}
		headFingerprint = head.EmptyGenesis.EmptyHeadFingerprint
	case *protocol.PromptQueueProjectionHead_Committed:
		if head.Committed == nil || head.Committed.CheckpointFingerprint == "" || head.Committed.HeadEventId == "" || head.Committed.HeadEventSequence == 0 || head.Committed.HeadEventPayloadFingerprint == "" || head.Committed.HeadReceiptFingerprint == "" || head.Committed.CommittedHeadFingerprint == "" || head.Committed.CheckpointTransitionCount+head.Committed.BoundedTailCount == 0 {
			return queueProjection{}, errors.New("committed queue head proof is invalid")
		}
		if head.Committed.BoundedTailCount == 0 {
			if head.Committed.BoundedTailFirstSequenceOrZero != 0 || head.Committed.BoundedTailLastSequenceOrZero != 0 || head.Committed.HeadEventSequence != head.Committed.CheckpointThroughSequence || head.Committed.CheckpointTransitionCount == 0 {
				return queueProjection{}, errors.New("checkpoint-only committed queue head proof is invalid")
			}
		} else if head.Committed.BoundedTailFirstSequenceOrZero <= head.Committed.CheckpointThroughSequence || head.Committed.BoundedTailLastSequenceOrZero != head.Committed.HeadEventSequence || head.Committed.BoundedTailFirstSequenceOrZero > head.Committed.BoundedTailLastSequenceOrZero {
			return queueProjection{}, errors.New("committed queue tail proof is invalid")
		}
		headFingerprint = head.Committed.CommittedHeadFingerprint
	default:
		return queueProjection{}, errors.New("queue head branch is unknown")
	}
	items := make([]QueueItem, 0, len(value.OrderedActiveItems))
	seen := map[string]bool{}
	lastOrdinal := uint64(0)
	for _, item := range value.OrderedActiveItems {
		if item == nil || item.QueueItemId == "" || item.AcceptedOrdinal == 0 || item.AcceptedOrdinal <= lastOrdinal || item.ViewFingerprint == "" || item.HeadEventId == "" || item.ItemRevision == 0 || seen[item.QueueItemId] || item.ContentRetentionState != protocol.PromptQueueContentRetentionState_PROMPT_QUEUE_CONTENT_ACTIVE || item.DeliveryState == protocol.PromptQueueDeliveryState_PROMPT_QUEUE_DELIVERY_STATE_UNSPECIFIED || item.RequestedDeliveryMode == protocol.PromptQueueRequestedDeliveryMode_PROMPT_QUEUE_REQUESTED_DELIVERY_MODE_UNSPECIFIED || item.ResolvedDeliveryMode == protocol.PromptQueueResolvedDeliveryMode_PROMPT_QUEUE_RESOLVED_DELIVERY_MODE_UNSPECIFIED || !publictext.IsSafe(item.PublicPreview) {
			return queueProjection{}, errors.New("active queue item is invalid")
		}
		seen[item.QueueItemId], lastOrdinal = true, item.AcceptedOrdinal
		items = append(items, QueueItem{ID: item.QueueItemId, AcceptedOrdinal: item.AcceptedOrdinal, PublicPreview: item.PublicPreview, HeadEventID: item.HeadEventId, Revision: item.ItemRevision, DeliveryState: item.DeliveryState, RequestedDeliveryMode: item.RequestedDeliveryMode, ResolvedDeliveryMode: item.ResolvedDeliveryMode, Fingerprint: item.ViewFingerprint})
	}
	return queueProjection{headFingerprint: headFingerprint, items: items}, nil
}

func OperationalSnapshotFromWire(frame *protocol.OperationalSnapshotFrame) (OperationalSnapshot, error) {
	if frame == nil || frame.RequestId == "" || frame.RuntimeSessionId == "" || frame.AttachmentId == "" || frame.AttachmentGeneration == 0 || frame.AttachmentIdentityFingerprint == "" || frame.AcknowledgedTransportBindingFingerprint == "" || frame.OperationalGeneration == 0 || frame.SnapshotFrameFingerprint == "" || frame.SnapshotContractFingerprint != OperationalContractFingerprint || frame.OperationalStateFingerprint == "" || frame.ActivityFingerprintAccumulator == "" {
		return OperationalSnapshot{}, errors.New("operational snapshot identity is incomplete")
	}
	if err := protocol.ValidateFingerprint("terminal-operational-snapshot-frame:v1", frame, "snapshot_frame_fingerprint", frame.SnapshotFrameFingerprint); err != nil {
		return OperationalSnapshot{}, err
	}
	if frame.ActivityCount != uint32(len(frame.OrderedActivityCells)) || frame.ActivityCount > MaximumOperationalActivities || frame.EncodedActivityBytes > MaximumOperationalBytes {
		return OperationalSnapshot{}, errors.New("operational snapshot bound is invalid")
	}
	cells := make([]OperationalCell, 0, len(frame.OrderedActivityCells))
	seen := map[string]bool{}
	lastCursor := uint64(0)
	lastCoalesceKey := ""
	for _, cell := range frame.OrderedActivityCells {
		if cell == nil {
			return OperationalSnapshot{}, errors.New("operational activity cell is empty")
		}
		var common *protocol.OperationalActivityCommon
		switch value := cell.Activity.(type) {
		case *protocol.OperationalActivityCell_ModelActivity:
			common = value.ModelActivity.Common
		case *protocol.OperationalActivityCell_ToolActivity:
			common = value.ToolActivity.Common
		case *protocol.OperationalActivityCell_TerminalProcessActivity:
			common = value.TerminalProcessActivity.Common
		case *protocol.OperationalActivityCell_SubagentActivity:
			common = value.SubagentActivity.Common
		default:
			return OperationalSnapshot{}, errors.New("unknown operational activity branch")
		}
		if common == nil || common.ActivityFingerprint == "" || common.CoalesceKey == "" || common.OwnerKind == "" || common.OwnerId == "" || common.OwnerGeneration == 0 || common.OperationalGeneration != frame.OperationalGeneration || common.OperationalCursor == 0 || common.OperationalCursor > frame.OperationalCursor || seen[common.CoalesceKey] || common.ReplacementSemantics == protocol.OperationalReplacementSemantics_OPERATIONAL_REPLACEMENT_SEMANTICS_UNSPECIFIED || !publictext.IsSafe(common.BoundedPublicText) {
			return OperationalSnapshot{}, errors.New("operational activity identity is invalid")
		}
		if common.OperationalCursor < lastCursor || (common.OperationalCursor == lastCursor && common.CoalesceKey <= lastCoalesceKey) {
			return OperationalSnapshot{}, errors.New("operational activity order is invalid")
		}
		lastCursor, lastCoalesceKey = common.OperationalCursor, common.CoalesceKey
		seen[common.CoalesceKey] = true
		cells = append(cells, OperationalCell{OwnerKind: common.OwnerKind, OwnerID: common.OwnerId, OwnerGeneration: common.OwnerGeneration, PublicText: common.BoundedPublicText, Fingerprint: common.ActivityFingerprint})
	}
	encoded, err := protocol.CanonicalProtobufJSONVectorBytes(frame.OrderedActivityCells)
	if err != nil || uint64(len(encoded)) != frame.EncodedActivityBytes {
		return OperationalSnapshot{}, errors.New("operational activity encoded byte count mismatch")
	}
	accumulator, err := protocol.OperationalActivityAccumulator(frame.OrderedActivityCells)
	if err != nil || accumulator != frame.ActivityFingerprintAccumulator {
		return OperationalSnapshot{}, errors.New("operational activity accumulator mismatch")
	}
	return OperationalSnapshot{
		RequestID: frame.RequestId, RuntimeSessionID: frame.RuntimeSessionId,
		AttachmentID: frame.AttachmentId, AttachmentGeneration: frame.AttachmentGeneration,
		AttachmentIdentityFingerprint:  frame.AttachmentIdentityFingerprint,
		AcknowledgedBindingFingerprint: frame.AcknowledgedTransportBindingFingerprint,
		Generation:                     frame.OperationalGeneration, Cursor: frame.OperationalCursor,
		Cells: cells, Count: frame.ActivityCount, EncodedBytes: frame.EncodedActivityBytes,
		Accumulator:         frame.ActivityFingerprintAccumulator,
		StateFingerprint:    frame.OperationalStateFingerprint,
		ContractFingerprint: frame.SnapshotContractFingerprint,
		FrameFingerprint:    frame.SnapshotFrameFingerprint,
	}, nil
}

func ValidateCapabilities(selected []protocol.TerminalClientCapability) error {
	if !sort.SliceIsSorted(selected, func(i, j int) bool { return selected[i] < selected[j] }) {
		return errors.New("selected terminal capabilities are not sorted")
	}
	seen := map[protocol.TerminalClientCapability]bool{}
	supported := make(map[protocol.TerminalClientCapability]bool, len(S1SupportedCapabilities))
	for _, capability := range S1SupportedCapabilities {
		supported[capability] = true
	}
	for _, capability := range selected {
		if capability == protocol.TerminalClientCapability_TERMINAL_CLIENT_CAPABILITY_UNSPECIFIED || seen[capability] || !supported[capability] {
			return errors.New("selected terminal capabilities are invalid")
		}
		seen[capability] = true
	}
	for _, required := range S1RequiredCapabilities {
		if !seen[required] {
			return fmt.Errorf("required terminal capability %s is missing", required)
		}
	}
	for _, forbidden := range []protocol.TerminalClientCapability{protocol.TerminalClientCapability_HISTORY_PAGE_V1, protocol.TerminalClientCapability_OBSERVATION_STREAM_V1, protocol.TerminalClientCapability_CONTROL_PROJECTION_OBSERVATION_V1, protocol.TerminalClientCapability_RECONNECT_AUTH_ROTATION_V1} {
		if seen[forbidden] {
			return fmt.Errorf("S1 over-advertised capability %s", forbidden)
		}
	}
	return nil
}

func ValidateSelectedProtocol(version *protocol.ProtocolVersion) error {
	if version == nil || version.Major != ProtocolMajor || version.Minor != ProtocolMinor || version.MinimumCompatibleMinor > ProtocolMinor || version.SchemaContractFingerprint != SchemaFingerprint {
		return errors.New("terminal protocol 2.0 compatibility check failed")
	}
	return nil
}

func PublicText(cell *protocol.DurableHistoryCell) (string, uint64, string, string, error) {
	if cell == nil || cell.Cell == nil {
		return "", 0, "", "", errors.New("durable history cell is empty")
	}
	var common *protocol.DurableCellCommon
	kind := ""
	switch value := cell.Cell.(type) {
	case *protocol.DurableHistoryCell_UserPrompt:
		kind, common = "user", value.UserPrompt.Common
	case *protocol.DurableHistoryCell_AssistantMessage:
		kind, common = "assistant", value.AssistantMessage.Common
	case *protocol.DurableHistoryCell_ToolTerminal:
		if value.ToolTerminal == nil || value.ToolTerminal.ResultState == protocol.PresentationToolResultState_PRESENTATION_TOOL_RESULT_STATE_UNSPECIFIED {
			return "", 0, "", "", errors.New("terminal tool result vocabulary is unknown")
		}
		kind, common = "tool", value.ToolTerminal.Common
	case *protocol.DurableHistoryCell_Error:
		kind, common = "error", value.Error.Common
	case *protocol.DurableHistoryCell_Interaction:
		if value.Interaction == nil || value.Interaction.InteractionKind == protocol.PresentationInteractionKind_PRESENTATION_INTERACTION_KIND_UNSPECIFIED || value.Interaction.InteractionState == protocol.PresentationInteractionState_PRESENTATION_INTERACTION_STATE_UNSPECIFIED {
			return "", 0, "", "", errors.New("terminal interaction vocabulary is unknown")
		}
		kind, common = "interaction", value.Interaction.Common
	case *protocol.DurableHistoryCell_CompactionBoundary:
		kind, common = "compaction", value.CompactionBoundary.Common
	case *protocol.DurableHistoryCell_Recovery:
		kind, common = "recovery", value.Recovery.Common
	case *protocol.DurableHistoryCell_Audit:
		if value.Audit == nil || value.Audit.AuditKind == protocol.PresentationAuditKind_PRESENTATION_AUDIT_KIND_UNSPECIFIED || value.Audit.Severity == protocol.PresentationSeverity_PRESENTATION_SEVERITY_UNSPECIFIED {
			return "", 0, "", "", errors.New("terminal audit vocabulary is unknown")
		}
		kind, common = "audit", value.Audit.Common
	case *protocol.DurableHistoryCell_SystemNotice:
		kind, common = "notice", value.SystemNotice.Common
	default:
		return "", 0, "", "", errors.New("unknown durable history cell branch")
	}
	if common == nil || common.StableCellId == "" || common.CellFingerprint == "" || common.VisibilityPolicy == protocol.PresentationVisibilityPolicy_PRESENTATION_VISIBILITY_POLICY_UNSPECIFIED {
		return "", 0, "", "", errors.New("durable history cell common fields are incomplete")
	}
	var builder strings.Builder
	for _, block := range common.ContentBlocks {
		if block == nil {
			return "", 0, "", "", errors.New("durable content block is empty")
		}
		switch content := block.Block.(type) {
		case *protocol.PresentationContentBlock_Text:
			if content.Text == nil || content.Text.SemanticRole == protocol.PresentationSemanticRole_PRESENTATION_SEMANTIC_ROLE_UNSPECIFIED || uint64(len([]byte(content.Text.Text))) != content.Text.TextUtf8Bytes || !publictext.IsSafe(content.Text.Text) {
				return "", 0, "", "", errors.New("terminal text byte count mismatch")
			}
			builder.WriteString(content.Text.Text)
		case *protocol.PresentationContentBlock_Data:
			if content.Data == nil || uint64(len([]byte(content.Data.PublicCanonicalText))) != content.Data.PublicUtf8Bytes || !publictext.IsSafe(content.Data.PublicCanonicalText) {
				return "", 0, "", "", errors.New("terminal data byte count mismatch")
			}
			builder.WriteString(content.Data.PublicCanonicalText)
		default:
			return "", 0, "", "", errors.New("unknown presentation content block")
		}
	}
	return kind, common.SemanticRevision, builder.String(), common.CellFingerprint, nil
}
