// Code generated by generate_terminal_protocol_contract.py. DO NOT EDIT.
package protocolvalue

import (
	"errors"
	"fmt"
	"strings"

	"github.com/plumliu/pulsara-agent/clients/terminal/internal/protocol"
	"google.golang.org/protobuf/proto"
)

var S2SupportedCapabilities = []protocol.TerminalClientCapability{
	protocol.TerminalClientCapability_PRESENTATION_SNAPSHOT_V1,
	protocol.TerminalClientCapability_OPERATIONAL_SNAPSHOT_V1,
	protocol.TerminalClientCapability_BOOTSTRAP_CARRIER_V1,
	protocol.TerminalClientCapability_LAUNCH_AUTH_PREFACE_V1,
	protocol.TerminalClientCapability_ATTACH_ACK_V1,
	protocol.TerminalClientCapability_HISTORY_PAGE_V1,
	protocol.TerminalClientCapability_OBSERVATION_STREAM_V1,
	protocol.TerminalClientCapability_ROOT_ADVANCE_V1,
	protocol.TerminalClientCapability_GAP_REBUILD_V1,
	protocol.TerminalClientCapability_CONTROL_PROJECTION_OBSERVATION_V1,
	protocol.TerminalClientCapability_RECONNECT_AUTH_ROTATION_V1,
}

var S2RequiredCapabilities = append([]protocol.TerminalClientCapability(nil), S2SupportedCapabilities...)

type ReconnectCredentialPublicIdentity struct {
	ID                                      string
	ClientInstanceID                        string
	PreviousAttachmentID                    string
	PreviousAttachmentGeneration            uint64
	ExpectedNextAttachmentAttemptGeneration uint64
	IssuedAtUTC                             string
	ExpiresAtUTC                            string
	Commitment                              string
	Fingerprint                             string
}

type ReconnectCredentialCarrier struct {
	PublicIdentity ReconnectCredentialPublicIdentity
	Capability     []byte
	Fingerprint    string
}

func ReconnectCredentialCarrierFromProto(value *protocol.ReconnectCredentialCarrier) (ReconnectCredentialCarrier, error) {
	if value == nil || value.PublicIdentity == nil || len(value.ReconnectCapability) != 32 || !validFingerprint(value.CarrierFingerprint) {
		return ReconnectCredentialCarrier{}, errors.New("terminal reconnect credential carrier is incomplete")
	}
	identity := value.PublicIdentity
	if identity.ReconnectCredentialId == "" || identity.ClientInstanceId == "" || identity.PreviousAttachmentId == "" ||
		identity.PreviousAttachmentGeneration == 0 || identity.ExpectedNextAttachmentAttemptGeneration == 0 ||
		identity.IssuedAtUtc == "" || identity.ExpiresAtUtc == "" || !validKeyedCommitment(identity.CredentialCommitment) ||
		!validFingerprint(identity.IdentityFingerprint) {
		return ReconnectCredentialCarrier{}, errors.New("terminal reconnect credential public identity is incomplete")
	}
	if err := protocol.ValidateFingerprint("terminal-reconnect-credential-public-identity:v1", identity, "identity_fingerprint", identity.IdentityFingerprint); err != nil {
		return ReconnectCredentialCarrier{}, err
	}
	if err := protocol.ValidateFingerprint("terminal-reconnect-credential-carrier:v1", value, "carrier_fingerprint", value.CarrierFingerprint); err != nil {
		return ReconnectCredentialCarrier{}, err
	}
	return ReconnectCredentialCarrier{
		PublicIdentity: ReconnectCredentialPublicIdentity{
			ID: identity.ReconnectCredentialId, ClientInstanceID: identity.ClientInstanceId,
			PreviousAttachmentID:                    identity.PreviousAttachmentId,
			PreviousAttachmentGeneration:            identity.PreviousAttachmentGeneration,
			ExpectedNextAttachmentAttemptGeneration: identity.ExpectedNextAttachmentAttemptGeneration,
			IssuedAtUTC:                             identity.IssuedAtUtc, ExpiresAtUTC: identity.ExpiresAtUtc,
			Commitment: identity.CredentialCommitment, Fingerprint: identity.IdentityFingerprint,
		},
		Capability:  append([]byte(nil), value.ReconnectCapability...),
		Fingerprint: value.CarrierFingerprint,
	}, nil
}

type HistoryRootIdentity struct {
	RuntimeSessionID              string
	ProjectionContractFingerprint string
	MaterializationFingerprint    string
	TreeContractFingerprint       string
	PlacementContractID           string
	PlacementContractVersion      string
	PlacementContractFingerprint  string
	CheckpointGeneration          uint64
	CheckpointFingerprint         string
	ProjectionGeneration          uint64
	ProjectionRootFingerprint     string
	ThroughAuthoritySequence      uint64
	SourceSegmentCount            uint64
	SourcePrefixAccumulator       string
	PolicyRegistryFingerprint     string
	AuditRegistryFingerprint      string
	RootFingerprint               string
}

type HistoryPlacementKey struct {
	ContractID             string
	ContractVersion        string
	ContractFingerprint    string
	HasLeftCoordinate      bool
	LeftCoordinate         uint64
	HasRightCoordinate     bool
	RightCoordinate        uint64
	RelativePosition       protocol.PresentationRelativePositionKind
	SourceLedgerSequence   uint64
	RelativeLocalOrdinal   uint32
	StableSourceTiebreaker string
	CanonicalComparableKey string
	Fingerprint            string
}

type HistoryCursor struct {
	RuntimeSessionID     string
	Root                 HistoryRootIdentity
	AnchorHistoryEntryID string
	AnchorPlacementKey   HistoryPlacementKey
	HasAnchor            bool
	Fingerprint          string
}

type RootCursorPair struct {
	Root        HistoryRootIdentity
	Before      HistoryCursor
	HasBefore   bool
	After       HistoryCursor
	HasAfter    bool
	Fingerprint string
}

type ActiveHead struct {
	RuntimeSessionID         string
	ConfirmedRoot            HistoryRootIdentity
	ThroughAuthoritySequence uint64
	ResidentEntryCount       uint64
	ResidentAccumulator      string
	Fingerprint              string
}

type HistoryChangeKind uint8

const (
	HistoryChangeUpsert HistoryChangeKind = iota + 1
	HistoryChangeRemove
)

type HistoryChange struct {
	Kind                        HistoryChangeKind
	HistoryEntryID              string
	PlacementKeyFingerprint     string
	ExpectedPreviousFingerprint string
	HasExpectedPrevious         bool
	Resulting                   HistoryCell
	ChangeFingerprint           string
}

type ProjectionDelta struct {
	RequestID                          string
	BaseRevision                       uint64
	ResultingRevision                  uint64
	ResultingAuthorityHighWater        uint64
	ResultingActiveHead                ActiveHead
	Changes                            []HistoryChange
	BaseResidentVectorFingerprint      string
	ResultingResidentVectorFingerprint string
	Fingerprint                        string
}

type AuthorityAdvance struct {
	RequestID                 string
	ProjectionRevision        uint64
	BaseActiveHeadFingerprint string
	ResultingActiveHead       ActiveHead
	Fingerprint               string
}

type ResidentTransitionKind uint8

const (
	ResidentTransitionUnchanged ResidentTransitionKind = iota + 1
	ResidentTransitionBoundedChanges
	ResidentTransitionRebaseRequired
)

type RootAdvance struct {
	RequestID                               string
	BaseRevision                            uint64
	ResultingRevision                       uint64
	PreviousActiveHeadFingerprint           string
	ResultingActiveHead                     ActiveHead
	LatestRootCursorPair                    RootCursorPair
	PreviousRoot                            HistoryRootIdentity
	ResultingRoot                           HistoryRootIdentity
	RootRelation                            protocol.PresentationRootRelationKind
	PreviousCursorDisposition               protocol.PresentationPreviousCursorDisposition
	SharedPrefixEntryCount                  uint64
	SharedPrefixAccumulator                 string
	RootRelationFingerprint                 string
	TransitionKind                          ResidentTransitionKind
	BeforeResidentFingerprint               string
	AfterResidentFingerprint                string
	TransitionProofFingerprint              string
	Changes                                 []HistoryChange
	ConsumedCheckpointCutFingerprint        string
	ConsumedTailPrefixThroughSequence       uint64
	ConsumedTailPrefixSourceAccumulator     string
	ConsumedTailPrefixSegmentCount          uint64
	ConsumedTailPrefixSegmentAccumulator    string
	ConsumedTailPrefixMutationCount         uint64
	ConsumedTailPrefixMutationAccumulator   string
	RetainedTailSuffixFromSequenceExclusive uint64
	RetainedTailSuffixThroughSequence       uint64
	RetainedTailSuffixSourceAccumulator     string
	RetainedTailSuffixSegmentCount          uint64
	RetainedTailSuffixSegmentAccumulator    string
	RetainedTailSuffixMutationCount         uint64
	RetainedTailSuffixMutationAccumulator   string
	CheckpointConfirmationFingerprint       string
	Fingerprint                             string
}

type GapReason = protocol.ObservationGapReason

type DurableGap struct {
	RequestID                string
	LatestAuthorityHighWater uint64
	LatestProjectionRevision uint64
	Reason                   GapReason
	Fingerprint              string
}

type OperationalChangeKind uint8

const (
	OperationalChangeUpsert OperationalChangeKind = iota + 1
	OperationalChangeRemove
)

type OperationalChange struct {
	Kind                        OperationalChangeKind
	Generation                  uint64
	Cursor                      uint64
	CoalesceKey                 string
	ExpectedPreviousFingerprint string
	Cell                        OperationalCell
	Fingerprint                 string
}

type OperationalDelta struct {
	RequestID   string
	Generation  uint64
	Cursor      uint64
	Changes     []OperationalChange
	Fingerprint string
}

type OperationalGap struct {
	RequestID        string
	LatestGeneration uint64
	LatestCursor     uint64
	Reason           GapReason
	Fingerprint      string
}

type ControlCursor struct {
	Generation            uint64
	Revision              uint64
	ProjectionFingerprint string
	TransitionAccumulator string
	RegistryFingerprint   string
	Fingerprint           string
}

type ControlChange struct {
	RequestID                 string
	ValidatedAfterFingerprint string
	BaseRevision              uint64
	BaseProjectionFingerprint string
	ResultingCursor           ControlCursor
	ChangedSections           []protocol.TerminalControlSectionKind
	ConsumedTransitionCount   uint64
	RangeAccumulator          string
	Fingerprint               string
}

type ControlGap struct {
	RequestID                  string
	RequestedCursorFingerprint string
	LatestCursor               ControlCursor
	Reason                     protocol.ControlProjectionGapReason
	Fingerprint                string
}

type ObservationBatch struct {
	RequestID        string
	ProjectionDelta  *ProjectionDelta
	AuthorityAdvance *AuthorityAdvance
	RootAdvance      *RootAdvance
	DurableGap       *DurableGap
	OperationalDelta *OperationalDelta
	OperationalGap   *OperationalGap
	ControlChange    *ControlChange
	ControlGap       *ControlGap
	PlaneCount       uint32
	Fingerprint      string
}

type ObservationNoChange struct {
	RequestID                string
	AuthorityHighWater       uint64
	ProjectionRevision       uint64
	OperationalGeneration    uint64
	OperationalCursor        uint64
	ControlCursorFingerprint string
	Fingerprint              string
}

type ObservationResult struct {
	Batch    ObservationBatch
	NoChange ObservationNoChange
	IsBatch  bool
}

type HistoryPageDirection = protocol.HistoryPageRequest_Direction

const (
	HistoryPageBefore = protocol.HistoryPageRequest_BEFORE
	HistoryPageAfter  = protocol.HistoryPageRequest_AFTER
)

type HistoryPageKind uint8

const (
	HistoryPageDataKind HistoryPageKind = iota + 1
	HistoryPageCursorStale
	HistoryPageRebaseRequired
	HistoryPageReconciliationRequired
)

type HistoryPageResult struct {
	Kind                        HistoryPageKind
	RequestID                   string
	RequestedCursorFingerprint  string
	Direction                   HistoryPageDirection
	Root                        HistoryRootIdentity
	Entries                     []HistoryCell
	decodedCarrierBytes         uint64
	BeforeCursor                HistoryCursor
	HasBeforeCursor             bool
	AfterCursor                 HistoryCursor
	HasAfterCursor              bool
	HasMoreBefore               bool
	HasMoreAfter                bool
	OrderedEntryAccumulator     string
	ContinuityProofFingerprint  string
	ReplacementCursor           HistoryCursor
	HasReplacementCursor        bool
	ReplacementProofFingerprint string
	FaultCode                   string
	ReconciliationOwnerIdentity string
	RetryAfterMS                uint32
	HasRetryAfter               bool
	Fingerprint                 string
}

func (value HistoryPageResult) DecodedCarrierBytes() uint64 {
	return value.decodedCarrierBytes
}

type ProjectionSnapshotOutcome struct {
	Snapshot                    DurableSnapshot
	RebaseRequired              bool
	RequestedMinimumFingerprint string
	LatestControlCursor         ControlCursor
	Fingerprint                 string
}

type PreparedProjectionSnapshotRequest struct {
	RequestID                    string
	RuntimeSessionID             string
	MinimumObservedControlCursor ControlCursor
	HasMinimum                   bool
	RequestFingerprint           string
}

type PreparedObserveRequest struct {
	RequestID               string
	AfterAuthorityHighWater uint64
	AfterProjectionRevision uint64
	AfterOperational        ControlIndependentOperationalCursor
	AfterControl            ControlCursor
	MaximumWaitMS           uint32
}

type ControlIndependentOperationalCursor struct {
	Generation uint64
	Cursor     uint64
}

type PreparedHistoryPageRequest struct {
	RequestID                string
	RuntimeSessionID         string
	Cursor                   HistoryCursor
	Direction                HistoryPageDirection
	MaximumCells             uint32
	MaximumDecodedBytes      uint32
	ProjectionContract       string
	ViewportIntentGeneration uint64
}

func (value ControlCursor) toProto() (*protocol.ControlProjectionCursor, error) {
	wire := &protocol.ControlProjectionCursor{
		ControlGeneration: value.Generation, ControlRevision: value.Revision,
		ControlProjectionFingerprint: value.ProjectionFingerprint,
		TransitionPrefixAccumulator:  value.TransitionAccumulator,
		RegistryContractFingerprint:  value.RegistryFingerprint,
		CursorFingerprint:            value.Fingerprint,
	}
	validated, err := controlCursorFromProto(wire)
	if err != nil || validated != value {
		if err != nil {
			return nil, err
		}
		return nil, errors.New("terminal control cursor carrier is inconsistent")
	}
	return wire, nil
}

func (value HistoryRootIdentity) toProto() (*protocol.PresentationHistoryRootIdentity, error) {
	wire := &protocol.PresentationHistoryRootIdentity{
		RuntimeSessionId:                              value.RuntimeSessionID,
		HistoryProjectionContractFingerprint:          value.ProjectionContractFingerprint,
		MaterializationPolicyFingerprint:              value.MaterializationFingerprint,
		TreeContractFingerprint:                       value.TreeContractFingerprint,
		PlacementKeyContractId:                        value.PlacementContractID,
		PlacementKeyContractVersion:                   value.PlacementContractVersion,
		PlacementKeyContractFingerprint:               value.PlacementContractFingerprint,
		CheckpointGeneration:                          value.CheckpointGeneration,
		CheckpointFingerprint:                         value.CheckpointFingerprint,
		ProjectionGeneration:                          value.ProjectionGeneration,
		ProjectionRootFingerprint:                     value.ProjectionRootFingerprint,
		ThroughAuthoritySequence:                      value.ThroughAuthoritySequence,
		PresentationSourceSegmentCount:                value.SourceSegmentCount,
		PresentationSourcePrefixAccumulator:           value.SourcePrefixAccumulator,
		PresentationPolicyRegistryContractFingerprint: value.PolicyRegistryFingerprint,
		AuditExtractorRegistryContractFingerprint:     value.AuditRegistryFingerprint,
		RootIdentityFingerprint:                       value.RootFingerprint,
	}
	validated, err := rootFromProto(wire)
	if err != nil || validated != value {
		if err != nil {
			return nil, err
		}
		return nil, errors.New("terminal history root carrier is inconsistent")
	}
	return wire, nil
}

func (value HistoryPlacementKey) toProto() (*protocol.PresentationHistoryPlacementKey, error) {
	wire := &protocol.PresentationHistoryPlacementKey{
		PlacementKeyContractId:          value.ContractID,
		PlacementKeyContractVersion:     value.ContractVersion,
		PlacementKeyContractFingerprint: value.ContractFingerprint,
		RelativePositionKind:            value.RelativePosition,
		SourceLedgerSequenceOrZero:      value.SourceLedgerSequence,
		RelativeLocalOrdinal:            value.RelativeLocalOrdinal,
		StableSourceTiebreaker:          value.StableSourceTiebreaker,
		CanonicalComparableKeyBytes:     []byte(value.CanonicalComparableKey),
		PlacementKeyFingerprint:         value.Fingerprint,
	}
	if value.HasLeftCoordinate {
		wire.CanonicalSpineLeftCoordinate = &value.LeftCoordinate
	}
	if value.HasRightCoordinate {
		wire.CanonicalSpineRightCoordinate = &value.RightCoordinate
	}
	validated, err := placementKeyFromProto(wire)
	if err != nil || validated != value {
		if err != nil {
			return nil, err
		}
		return nil, errors.New("terminal history placement carrier is inconsistent")
	}
	return wire, nil
}

func (value HistoryCursor) toProto() (*protocol.PresentationHistoryCursor, error) {
	root, err := value.Root.toProto()
	if err != nil {
		return nil, err
	}
	wire := &protocol.PresentationHistoryCursor{
		RuntimeSessionId:  value.RuntimeSessionID,
		RootIdentity:      root,
		CursorFingerprint: value.Fingerprint,
	}
	if value.HasAnchor {
		placement, placementErr := value.AnchorPlacementKey.toProto()
		if placementErr != nil {
			return nil, placementErr
		}
		wire.AnchorHistoryEntryId = &value.AnchorHistoryEntryID
		wire.AnchorPlacementKey = placement
	}
	validated, err := cursorFromProto(wire)
	if err != nil || validated != value {
		if err != nil {
			return nil, err
		}
		return nil, errors.New("terminal history cursor carrier is inconsistent")
	}
	return wire, nil
}

func PrepareProjectionSnapshotRequest(requestID, runtimeSessionID string, minimum *ControlCursor) (PreparedProjectionSnapshotRequest, error) {
	if requestID == "" || runtimeSessionID == "" {
		return PreparedProjectionSnapshotRequest{}, errors.New("terminal projection snapshot request identity is incomplete")
	}
	wire := &protocol.ProjectionSnapshotRequest{RequestId: requestID, RuntimeSessionId: runtimeSessionID}
	result := PreparedProjectionSnapshotRequest{RequestID: requestID, RuntimeSessionID: runtimeSessionID}
	if minimum != nil {
		cursor, err := minimum.toProto()
		if err != nil {
			return PreparedProjectionSnapshotRequest{}, err
		}
		wire.MinimumObservedControlCursor = cursor
		result.MinimumObservedControlCursor, result.HasMinimum = *minimum, true
	}
	if _, err := protocol.InstallFingerprint("terminal-projection-snapshot-request:v2", wire, "request_fingerprint"); err != nil {
		return PreparedProjectionSnapshotRequest{}, err
	}
	result.RequestFingerprint = wire.RequestFingerprint
	return result, nil
}

func (value PreparedProjectionSnapshotRequest) ToProto() (*protocol.ProjectionSnapshotRequest, error) {
	var minimum *ControlCursor
	if value.HasMinimum {
		minimum = &value.MinimumObservedControlCursor
	}
	prepared, err := PrepareProjectionSnapshotRequest(value.RequestID, value.RuntimeSessionID, minimum)
	if err != nil || prepared != value {
		if err != nil {
			return nil, err
		}
		return nil, errors.New("terminal projection snapshot request carrier is inconsistent")
	}
	wire := &protocol.ProjectionSnapshotRequest{RequestId: value.RequestID, RuntimeSessionId: value.RuntimeSessionID, RequestFingerprint: value.RequestFingerprint}
	if value.HasMinimum {
		wire.MinimumObservedControlCursor, err = value.MinimumObservedControlCursor.toProto()
		if err != nil {
			return nil, err
		}
	}
	return wire, nil
}

func PrepareObserveRequest(requestID string, authorityHighWater, projectionRevision, operationalGeneration, operationalCursor uint64, control ControlCursor, maximumWaitMS uint32) (PreparedObserveRequest, error) {
	if requestID == "" || maximumWaitMS == 0 || maximumWaitMS > 30_000 {
		return PreparedObserveRequest{}, errors.New("terminal observe request bounds are invalid")
	}
	if _, err := control.toProto(); err != nil {
		return PreparedObserveRequest{}, err
	}
	return PreparedObserveRequest{RequestID: requestID, AfterAuthorityHighWater: authorityHighWater, AfterProjectionRevision: projectionRevision, AfterOperational: ControlIndependentOperationalCursor{Generation: operationalGeneration, Cursor: operationalCursor}, AfterControl: control, MaximumWaitMS: maximumWaitMS}, nil
}

func (value PreparedObserveRequest) ToProto() (*protocol.ObserveNextRequest, error) {
	control, err := value.AfterControl.toProto()
	if err != nil {
		return nil, err
	}
	wire := &protocol.ObserveNextRequest{RequestId: value.RequestID, AfterAuthorityHighWater: value.AfterAuthorityHighWater, AfterProjectionRevision: value.AfterProjectionRevision, AfterOperationalGeneration: value.AfterOperational.Generation, AfterOperationalCursor: value.AfterOperational.Cursor, AfterControlCursor: control, MaximumWaitMs: value.MaximumWaitMS}
	prepared, err := PrepareObserveRequest(wire.RequestId, wire.AfterAuthorityHighWater, wire.AfterProjectionRevision, wire.AfterOperationalGeneration, wire.AfterOperationalCursor, value.AfterControl, wire.MaximumWaitMs)
	if err != nil || prepared != value {
		if err != nil {
			return nil, err
		}
		return nil, errors.New("terminal observe request carrier is inconsistent")
	}
	return wire, nil
}

func PrepareHistoryPageRequest(requestID, runtimeSessionID string, cursor HistoryCursor, direction HistoryPageDirection, maximumCells, maximumDecodedBytes uint32, projectionContract string, intentGeneration uint64) (PreparedHistoryPageRequest, error) {
	if requestID == "" || runtimeSessionID == "" || cursor.RuntimeSessionID != runtimeSessionID ||
		(direction != HistoryPageBefore && direction != HistoryPageAfter) || maximumCells == 0 || maximumCells > MaximumHistoryPageCells ||
		maximumDecodedBytes == 0 || maximumDecodedBytes > MaximumHistoryPageDecodedBytes || projectionContract == "" || intentGeneration == 0 {
		return PreparedHistoryPageRequest{}, errors.New("terminal history page request is invalid")
	}
	if _, err := cursor.toProto(); err != nil {
		return PreparedHistoryPageRequest{}, err
	}
	return PreparedHistoryPageRequest{RequestID: requestID, RuntimeSessionID: runtimeSessionID, Cursor: cursor, Direction: direction, MaximumCells: maximumCells, MaximumDecodedBytes: maximumDecodedBytes, ProjectionContract: projectionContract, ViewportIntentGeneration: intentGeneration}, nil
}

func (value PreparedHistoryPageRequest) ToProto() (*protocol.HistoryPageRequest, error) {
	cursor, err := value.Cursor.toProto()
	if err != nil {
		return nil, err
	}
	return &protocol.HistoryPageRequest{RequestId: value.RequestID, RuntimeSessionId: value.RuntimeSessionID, Cursor: cursor, Direction: value.Direction, MaximumCells: value.MaximumCells, MaximumDecodedBytes: value.MaximumDecodedBytes, ExpectedProjectionContractFingerprint: value.ProjectionContract}, nil
}

func controlCursorFromProto(value *protocol.ControlProjectionCursor) (ControlCursor, error) {
	if value == nil || value.ControlGeneration == 0 || value.ControlRevision == 0 || value.ControlProjectionFingerprint == "" || value.TransitionPrefixAccumulator == "" || value.RegistryContractFingerprint == "" || !validFingerprint(value.CursorFingerprint) {
		return ControlCursor{}, errors.New("terminal control cursor is incomplete")
	}
	return ControlCursor{Generation: value.ControlGeneration, Revision: value.ControlRevision, ProjectionFingerprint: value.ControlProjectionFingerprint, TransitionAccumulator: value.TransitionPrefixAccumulator, RegistryFingerprint: value.RegistryContractFingerprint, Fingerprint: value.CursorFingerprint}, nil
}

func rootFromProto(value *protocol.PresentationHistoryRootIdentity) (HistoryRootIdentity, error) {
	if value == nil || value.RuntimeSessionId == "" || value.HistoryProjectionContractFingerprint == "" ||
		value.MaterializationPolicyFingerprint == "" || value.TreeContractFingerprint == "" ||
		value.PlacementKeyContractId == "" || value.PlacementKeyContractVersion == "" || value.PlacementKeyContractFingerprint == "" ||
		value.CheckpointFingerprint == "" || value.ProjectionGeneration == 0 || value.ProjectionRootFingerprint == "" ||
		value.PresentationSourcePrefixAccumulator == "" || value.PresentationPolicyRegistryContractFingerprint == "" ||
		value.AuditExtractorRegistryContractFingerprint == "" || !validFingerprint(value.RootIdentityFingerprint) {
		return HistoryRootIdentity{}, errors.New("terminal history root identity is incomplete")
	}
	return HistoryRootIdentity{RuntimeSessionID: value.RuntimeSessionId, ProjectionContractFingerprint: value.HistoryProjectionContractFingerprint, MaterializationFingerprint: value.MaterializationPolicyFingerprint, TreeContractFingerprint: value.TreeContractFingerprint, PlacementContractID: value.PlacementKeyContractId, PlacementContractVersion: value.PlacementKeyContractVersion, PlacementContractFingerprint: value.PlacementKeyContractFingerprint, CheckpointGeneration: value.CheckpointGeneration, CheckpointFingerprint: value.CheckpointFingerprint, ProjectionGeneration: value.ProjectionGeneration, ProjectionRootFingerprint: value.ProjectionRootFingerprint, ThroughAuthoritySequence: value.ThroughAuthoritySequence, SourceSegmentCount: value.PresentationSourceSegmentCount, SourcePrefixAccumulator: value.PresentationSourcePrefixAccumulator, PolicyRegistryFingerprint: value.PresentationPolicyRegistryContractFingerprint, AuditRegistryFingerprint: value.AuditExtractorRegistryContractFingerprint, RootFingerprint: value.RootIdentityFingerprint}, nil
}

func placementKeyFromProto(value *protocol.PresentationHistoryPlacementKey) (HistoryPlacementKey, error) {
	if value == nil || value.PlacementKeyContractId == "" || value.PlacementKeyContractVersion == "" ||
		value.PlacementKeyContractFingerprint == "" || !validRelativePositionKind(value.RelativePositionKind) ||
		value.StableSourceTiebreaker == "" || len(value.CanonicalComparableKeyBytes) == 0 || !validFingerprint(value.PlacementKeyFingerprint) {
		return HistoryPlacementKey{}, errors.New("terminal history placement identity is incomplete")
	}
	result := HistoryPlacementKey{
		ContractID: value.PlacementKeyContractId, ContractVersion: value.PlacementKeyContractVersion,
		ContractFingerprint: value.PlacementKeyContractFingerprint, RelativePosition: value.RelativePositionKind,
		SourceLedgerSequence: value.SourceLedgerSequenceOrZero, RelativeLocalOrdinal: value.RelativeLocalOrdinal,
		StableSourceTiebreaker: value.StableSourceTiebreaker, CanonicalComparableKey: string(value.CanonicalComparableKeyBytes),
		Fingerprint: value.PlacementKeyFingerprint,
	}
	if value.CanonicalSpineLeftCoordinate != nil {
		result.HasLeftCoordinate, result.LeftCoordinate = true, *value.CanonicalSpineLeftCoordinate
	}
	if value.CanonicalSpineRightCoordinate != nil {
		result.HasRightCoordinate, result.RightCoordinate = true, *value.CanonicalSpineRightCoordinate
	}
	return result, nil
}

func validRelativePositionKind(value protocol.PresentationRelativePositionKind) bool {
	switch value {
	case protocol.PresentationRelativePositionKind_PRESENTATION_RELATIVE_POSITION_BEFORE_FIRST,
		protocol.PresentationRelativePositionKind_PRESENTATION_RELATIVE_POSITION_BEFORE_LEAF,
		protocol.PresentationRelativePositionKind_PRESENTATION_RELATIVE_POSITION_CANONICAL_LEAF,
		protocol.PresentationRelativePositionKind_PRESENTATION_RELATIVE_POSITION_AFTER_LEAF,
		protocol.PresentationRelativePositionKind_PRESENTATION_RELATIVE_POSITION_LEDGER_GAP,
		protocol.PresentationRelativePositionKind_PRESENTATION_RELATIVE_POSITION_AFTER_LAST:
		return true
	default:
		return false
	}
}

func cursorFromProto(value *protocol.PresentationHistoryCursor) (HistoryCursor, error) {
	if value == nil || value.RuntimeSessionId == "" || !validFingerprint(value.CursorFingerprint) {
		return HistoryCursor{}, errors.New("terminal history cursor is incomplete")
	}
	root, err := rootFromProto(value.RootIdentity)
	if err != nil || root.RuntimeSessionID != value.RuntimeSessionId {
		return HistoryCursor{}, errors.New("terminal history cursor root is stale")
	}
	hasID, hasKey := value.AnchorHistoryEntryId != nil, value.AnchorPlacementKey != nil
	if hasID != hasKey {
		return HistoryCursor{}, errors.New("terminal history cursor anchor is partial")
	}
	result := HistoryCursor{RuntimeSessionID: value.RuntimeSessionId, Root: root, HasAnchor: hasID, Fingerprint: value.CursorFingerprint}
	if hasID {
		if *value.AnchorHistoryEntryId == "" {
			return HistoryCursor{}, errors.New("terminal history cursor anchor is invalid")
		}
		placement, placementErr := placementKeyFromProto(value.AnchorPlacementKey)
		if placementErr != nil {
			return HistoryCursor{}, placementErr
		}
		if placement.ContractID != root.PlacementContractID ||
			placement.ContractVersion != root.PlacementContractVersion ||
			placement.ContractFingerprint != root.PlacementContractFingerprint {
			return HistoryCursor{}, errors.New("terminal history cursor placement contract crosses root authority")
		}
		result.AnchorHistoryEntryID = *value.AnchorHistoryEntryId
		result.AnchorPlacementKey = placement
	}
	return result, nil
}

func cursorPairFromProto(value *protocol.PresentationHistoryLatestRootCursorPair) (RootCursorPair, error) {
	if value == nil || !validFingerprint(value.CursorPairFingerprint) {
		return RootCursorPair{}, errors.New("terminal root cursor pair is incomplete")
	}
	root, err := rootFromProto(value.RootIdentity)
	if err != nil {
		return RootCursorPair{}, err
	}
	result := RootCursorPair{Root: root, Fingerprint: value.CursorPairFingerprint}
	if value.BeforeCursor != nil {
		result.Before, err = cursorFromProto(value.BeforeCursor)
		if err != nil || result.Before.Root != root {
			return RootCursorPair{}, errors.New("terminal before cursor crosses roots")
		}
		result.HasBefore = true
	}
	if value.AfterCursor != nil {
		result.After, err = cursorFromProto(value.AfterCursor)
		if err != nil || result.After.Root != root {
			return RootCursorPair{}, errors.New("terminal after cursor crosses roots")
		}
		result.HasAfter = true
	}
	return result, nil
}

func activeHeadFromProto(value *protocol.PresentationHistoryActiveHeadIdentity) (ActiveHead, error) {
	if value == nil || value.RuntimeSessionId == "" || !validFingerprint(value.ActiveHeadFingerprint) || value.ResultingResidentEntryAccumulator == "" {
		return ActiveHead{}, errors.New("terminal active head is incomplete")
	}
	root, err := rootFromProto(value.ConfirmedRootIdentity)
	if err != nil || root.RuntimeSessionID != value.RuntimeSessionId || value.TailFromSequenceExclusive != root.ThroughAuthoritySequence || value.ThroughAuthoritySequence < root.ThroughAuthoritySequence {
		return ActiveHead{}, errors.New("terminal active head root join is invalid")
	}
	return ActiveHead{RuntimeSessionID: value.RuntimeSessionId, ConfirmedRoot: root, ThroughAuthoritySequence: value.ThroughAuthoritySequence, ResidentEntryCount: value.ResultingResidentEntryCount, ResidentAccumulator: value.ResultingResidentEntryAccumulator, Fingerprint: value.ActiveHeadFingerprint}, nil
}

func historyCellFromRanked(value *protocol.PresentationHistoryRankedEntry) (HistoryCell, error) {
	if value == nil || value.Entry == nil || value.Entry.PlacementKey == nil || value.Entry.HistoryEntryId == "" || !validFingerprint(value.Entry.EntryFingerprint) || !validFingerprint(value.Entry.PlacementKey.PlacementKeyFingerprint) || !validFingerprint(value.RankedViewFingerprint) {
		return HistoryCell{}, errors.New("terminal ranked history entry is incomplete")
	}
	kind, revision, text, cellFingerprint, err := PublicText(value.Entry.DurableHistoryCell)
	if err != nil {
		return HistoryCell{}, err
	}
	return HistoryCell{ID: value.Entry.HistoryEntryId, Revision: revision, Kind: kind, PublicText: text, Fingerprint: value.Entry.EntryFingerprint, CellFingerprint: cellFingerprint, PlacementKeyFingerprint: value.Entry.PlacementKey.PlacementKeyFingerprint, DisplayRank: value.RootLocalDisplayRank, RankedFingerprint: value.RankedViewFingerprint}, nil
}

func historyChangeFromProto(value *protocol.HistoryEntryChange) (HistoryChange, error) {
	if value == nil {
		return HistoryChange{}, errors.New("terminal history change is empty")
	}
	switch branch := value.Change.(type) {
	case *protocol.HistoryEntryChange_Upsert:
		item := branch.Upsert
		if item == nil || item.PlacementKey == nil || item.HistoryEntryId == "" || !validFingerprint(item.PlacementKey.PlacementKeyFingerprint) || !validFingerprint(item.ChangeFingerprint) {
			return HistoryChange{}, errors.New("terminal history upsert is incomplete")
		}
		cell, err := historyCellFromRanked(item.ResultingRankedEntry)
		if err != nil || cell.ID != item.HistoryEntryId || cell.PlacementKeyFingerprint != item.PlacementKey.PlacementKeyFingerprint {
			return HistoryChange{}, errors.New("terminal history upsert result is stale")
		}
		result := HistoryChange{Kind: HistoryChangeUpsert, HistoryEntryID: item.HistoryEntryId, PlacementKeyFingerprint: item.PlacementKey.PlacementKeyFingerprint, Resulting: cell, ChangeFingerprint: item.ChangeFingerprint}
		if item.ExpectedPreviousEntryFingerprint != nil {
			result.HasExpectedPrevious = true
			result.ExpectedPreviousFingerprint = *item.ExpectedPreviousEntryFingerprint
		}
		return result, nil
	case *protocol.HistoryEntryChange_Remove:
		item := branch.Remove
		if item == nil || item.PlacementKey == nil || item.HistoryEntryId == "" || !validFingerprint(item.ExpectedPreviousEntryFingerprint) || !validFingerprint(item.ChangeFingerprint) {
			return HistoryChange{}, errors.New("terminal history remove is incomplete")
		}
		return HistoryChange{Kind: HistoryChangeRemove, HistoryEntryID: item.HistoryEntryId, PlacementKeyFingerprint: item.PlacementKey.PlacementKeyFingerprint, ExpectedPreviousFingerprint: item.ExpectedPreviousEntryFingerprint, HasExpectedPrevious: true, ChangeFingerprint: item.ChangeFingerprint}, nil
	default:
		return HistoryChange{}, errors.New("terminal history change branch is unknown")
	}
}

func operationalCommon(value *protocol.OperationalActivityCell) (*protocol.OperationalActivityCommon, error) {
	if value == nil {
		return nil, errors.New("terminal operational cell is empty")
	}
	var common *protocol.OperationalActivityCommon
	switch branch := value.Activity.(type) {
	case *protocol.OperationalActivityCell_ModelActivity:
		common = branch.ModelActivity.GetCommon()
	case *protocol.OperationalActivityCell_ToolActivity:
		common = branch.ToolActivity.GetCommon()
	case *protocol.OperationalActivityCell_TerminalProcessActivity:
		common = branch.TerminalProcessActivity.GetCommon()
	case *protocol.OperationalActivityCell_SubagentActivity:
		common = branch.SubagentActivity.GetCommon()
	}
	if common == nil || common.OwnerKind == "" || common.OwnerId == "" || common.OwnerGeneration == 0 || common.OperationalGeneration == 0 || common.OperationalCursor == 0 || common.CoalesceKey == "" || !validFingerprint(common.ActivityFingerprint) {
		return nil, errors.New("terminal operational cell common fields are invalid")
	}
	return common, nil
}

func operationalChangeFromProto(value *protocol.OperationalActivityChange) (OperationalChange, error) {
	if value == nil {
		return OperationalChange{}, errors.New("terminal operational change is empty")
	}
	switch branch := value.Change.(type) {
	case *protocol.OperationalActivityChange_Upsert:
		common, err := operationalCommon(branch.Upsert)
		if err != nil {
			return OperationalChange{}, err
		}
		cell := OperationalCell{OwnerKind: common.OwnerKind, OwnerID: common.OwnerId, OwnerGeneration: common.OwnerGeneration, Generation: common.OperationalGeneration, Cursor: common.OperationalCursor, CoalesceKey: common.CoalesceKey, PublicText: common.BoundedPublicText, Fingerprint: common.ActivityFingerprint}
		return OperationalChange{Kind: OperationalChangeUpsert, Generation: common.OperationalGeneration, Cursor: common.OperationalCursor, CoalesceKey: common.CoalesceKey, Cell: cell, Fingerprint: common.ActivityFingerprint}, nil
	case *protocol.OperationalActivityChange_Remove:
		item := branch.Remove
		if item == nil || item.OperationalGeneration == 0 || item.OperationalCursor == 0 || item.CoalesceKey == "" || !validFingerprint(item.ExpectedActivityFingerprint) || !validFingerprint(item.RemovalFingerprint) {
			return OperationalChange{}, errors.New("terminal operational removal is incomplete")
		}
		return OperationalChange{Kind: OperationalChangeRemove, Generation: item.OperationalGeneration, Cursor: item.OperationalCursor, CoalesceKey: item.CoalesceKey, ExpectedPreviousFingerprint: item.ExpectedActivityFingerprint, Fingerprint: item.RemovalFingerprint}, nil
	default:
		return OperationalChange{}, errors.New("terminal operational change branch is unknown")
	}
}

func ObservationFromProto(value *protocol.ObservationResponse) (ObservationResult, error) {
	if value == nil {
		return ObservationResult{}, errors.New("terminal observation response is empty")
	}
	if noChange := value.GetNoChange(); noChange != nil {
		if noChange.RequestId == "" || !validFingerprint(noChange.FrameFingerprint) || noChange.EchoedControlCursorFingerprint == "" {
			return ObservationResult{}, errors.New("terminal no-change observation is incomplete")
		}
		if err := protocol.ValidateFingerprint("terminal-observation-no-change:v1", noChange, "frame_fingerprint", noChange.FrameFingerprint); err != nil {
			return ObservationResult{}, err
		}
		return ObservationResult{NoChange: ObservationNoChange{RequestID: noChange.RequestId, AuthorityHighWater: noChange.EchoedAuthorityHighWater, ProjectionRevision: noChange.EchoedProjectionRevision, OperationalGeneration: noChange.EchoedOperationalGeneration, OperationalCursor: noChange.EchoedOperationalCursor, ControlCursorFingerprint: noChange.EchoedControlCursorFingerprint, Fingerprint: noChange.FrameFingerprint}}, nil
	}
	batch := value.GetBatch()
	if batch == nil || batch.RequestId == "" || batch.IncludedPlaneCount == 0 || batch.IncludedPlaneCount > 3 || !validFingerprint(batch.BatchFingerprint) {
		return ObservationResult{}, errors.New("terminal observation batch is incomplete")
	}
	if err := protocol.ValidateFingerprint("terminal-observation-batch:v1", batch, "batch_fingerprint", batch.BatchFingerprint); err != nil {
		return ObservationResult{}, err
	}
	result := ObservationBatch{RequestID: batch.RequestId, PlaneCount: batch.IncludedPlaneCount, Fingerprint: batch.BatchFingerprint}
	present := uint32(0)
	if batch.Control != nil {
		present++
		if changed := batch.Control.GetChanged(); changed != nil {
			cursor, err := controlCursorFromProto(changed.ResultingControlCursor)
			if err != nil || changed.RequestId != batch.RequestId || changed.ValidatedAfterControlCursorFingerprint == "" || changed.ControlGeneration != cursor.Generation || changed.ResultingControlProjectionRevision != cursor.Revision || changed.ResultingControlProjectionFingerprint != cursor.ProjectionFingerprint || changed.ResultingControlProjectionRevision <= changed.BaseControlProjectionRevision || changed.ConsumedTransitionCount == 0 || !validFingerprint(changed.ConsumedTransitionRangeAccumulator) || changed.Disposition != protocol.ControlProjectionInvalidationDisposition_CONTROL_PROJECTION_SNAPSHOT_REQUIRED || !validControlSections(changed.ChangedSections) || !validFingerprint(changed.FrameFingerprint) {
				return ObservationResult{}, errors.New("terminal control change is invalid")
			}
			sections := append([]protocol.TerminalControlSectionKind(nil), changed.ChangedSections...)
			result.ControlChange = &ControlChange{RequestID: changed.RequestId, ValidatedAfterFingerprint: changed.ValidatedAfterControlCursorFingerprint, BaseRevision: changed.BaseControlProjectionRevision, BaseProjectionFingerprint: changed.BaseControlProjectionFingerprint, ResultingCursor: cursor, ChangedSections: sections, ConsumedTransitionCount: changed.ConsumedTransitionCount, RangeAccumulator: changed.ConsumedTransitionRangeAccumulator, Fingerprint: changed.FrameFingerprint}
		} else if gap := batch.Control.GetGap(); gap != nil {
			cursor, err := controlCursorFromProto(gap.LatestControlCursor)
			if err != nil || gap.RequestId != batch.RequestId || gap.RequestedControlCursorFingerprint == "" || gap.StableReason == protocol.ControlProjectionGapReason_CONTROL_PROJECTION_GAP_REASON_UNSPECIFIED || gap.Disposition != protocol.ControlProjectionInvalidationDisposition_CONTROL_PROJECTION_SNAPSHOT_REQUIRED || !validFingerprint(gap.FrameFingerprint) {
				return ObservationResult{}, errors.New("terminal control gap is invalid")
			}
			result.ControlGap = &ControlGap{RequestID: gap.RequestId, RequestedCursorFingerprint: gap.RequestedControlCursorFingerprint, LatestCursor: cursor, Reason: gap.StableReason, Fingerprint: gap.FrameFingerprint}
		} else {
			return ObservationResult{}, errors.New("terminal control observation branch is unknown")
		}
	}
	if batch.Durable != nil {
		present++
		switch branch := batch.Durable.Outcome.(type) {
		case *protocol.DurableObservationBranch_ProjectionDelta:
			item := branch.ProjectionDelta
			head, err := activeHeadFromProto(item.ResultingActiveHead)
			if err != nil || item.RequestId != batch.RequestId || item.ResultingProjectionRevision != item.BaseProjectionRevision+1 || item.ResultingAuthorityHighWater != head.ThroughAuthoritySequence || !validFingerprint(item.DeltaFingerprint) || !validFingerprint(item.BaseResidentVectorFingerprint) || !validFingerprint(item.ResultingResidentVectorFingerprint) {
				return ObservationResult{}, errors.New("terminal projection delta is invalid")
			}
			changes := make([]HistoryChange, 0, len(item.OrderedHistoryChanges))
			for _, raw := range item.OrderedHistoryChanges {
				change, err := historyChangeFromProto(raw)
				if err != nil {
					return ObservationResult{}, err
				}
				changes = append(changes, change)
			}
			result.ProjectionDelta = &ProjectionDelta{RequestID: item.RequestId, BaseRevision: item.BaseProjectionRevision, ResultingRevision: item.ResultingProjectionRevision, ResultingAuthorityHighWater: item.ResultingAuthorityHighWater, ResultingActiveHead: head, Changes: changes, BaseResidentVectorFingerprint: item.BaseResidentVectorFingerprint, ResultingResidentVectorFingerprint: item.ResultingResidentVectorFingerprint, Fingerprint: item.DeltaFingerprint}
		case *protocol.DurableObservationBranch_AuthorityAdvance:
			item := branch.AuthorityAdvance
			head, err := activeHeadFromProto(item.ResultingActiveHead)
			if err != nil || item.RequestId != batch.RequestId || !validFingerprint(item.FrameFingerprint) {
				return ObservationResult{}, errors.New("terminal authority advance is invalid")
			}
			result.AuthorityAdvance = &AuthorityAdvance{RequestID: item.RequestId, ProjectionRevision: item.ProjectionRevision, BaseActiveHeadFingerprint: item.BaseActiveHeadFingerprint, ResultingActiveHead: head, Fingerprint: item.FrameFingerprint}
		case *protocol.DurableObservationBranch_RootAdvanced:
			item := branch.RootAdvanced
			head, err := activeHeadFromProto(item.ResultingActiveHead)
			if err != nil || item.RequestId != batch.RequestId || item.ResultingProjectionRevision != item.BaseProjectionRevision+1 || !validFingerprint(item.FrameFingerprint) || item.PreviousRootRelation == nil || item.ResidentTransition == nil {
				return ObservationResult{}, errors.New("terminal root advance is invalid")
			}
			pair, err := cursorPairFromProto(item.LatestRootCursorPair)
			if err != nil {
				return ObservationResult{}, err
			}
			previous, err := rootFromProto(item.PreviousRootRelation.PreviousRootIdentity)
			if err != nil {
				return ObservationResult{}, err
			}
			resulting, err := rootFromProto(item.PreviousRootRelation.ResultingRootIdentity)
			if err != nil {
				return ObservationResult{}, err
			}
			relation := item.PreviousRootRelation
			if relation.Relation == protocol.PresentationRootRelationKind_PRESENTATION_ROOT_RELATION_KIND_UNSPECIFIED || relation.PreviousCursor != protocol.PresentationPreviousCursorDisposition_RETAINED_PINNED || !validFingerprint(relation.SharedPrefixAccumulator) || !validFingerprint(relation.RelationFingerprint) || previous.RootFingerprint == resulting.RootFingerprint || resulting.RootFingerprint != head.ConfirmedRoot.RootFingerprint || pair.Root.RootFingerprint != resulting.RootFingerprint || item.ConsumedTailPrefixThroughSequence != resulting.ThroughAuthoritySequence || item.RetainedTailSuffixFromSequenceExclusive != item.ConsumedTailPrefixThroughSequence || item.RetainedTailSuffixThroughSequence != head.ThroughAuthoritySequence || !validFingerprint(item.ConsumedCheckpointCandidateCutFingerprint) || !validFingerprint(item.ConsumedTailPrefixSourceRangeAccumulator) || !validFingerprint(item.ConsumedTailPrefixSegmentAccumulator) || !validFingerprint(item.ConsumedTailPrefixMutationAccumulator) || !validFingerprint(item.RetainedTailSuffixSourceRangeAccumulator) || !validFingerprint(item.RetainedTailSuffixSegmentAccumulator) || !validFingerprint(item.RetainedTailSuffixMutationAccumulator) || !validFingerprint(item.CheckpointFullConfirmationFingerprint) {
				return ObservationResult{}, errors.New("terminal root advance continuity proof is invalid")
			}
			advance := &RootAdvance{RequestID: item.RequestId, BaseRevision: item.BaseProjectionRevision, ResultingRevision: item.ResultingProjectionRevision, PreviousActiveHeadFingerprint: item.PreviousActiveHeadFingerprint, ResultingActiveHead: head, LatestRootCursorPair: pair, PreviousRoot: previous, ResultingRoot: resulting, RootRelation: relation.Relation, PreviousCursorDisposition: relation.PreviousCursor, SharedPrefixEntryCount: relation.SharedPrefixEntryCount, SharedPrefixAccumulator: relation.SharedPrefixAccumulator, RootRelationFingerprint: relation.RelationFingerprint, ConsumedCheckpointCutFingerprint: item.ConsumedCheckpointCandidateCutFingerprint, ConsumedTailPrefixThroughSequence: item.ConsumedTailPrefixThroughSequence, ConsumedTailPrefixSourceAccumulator: item.ConsumedTailPrefixSourceRangeAccumulator, ConsumedTailPrefixSegmentCount: item.ConsumedTailPrefixSegmentCount, ConsumedTailPrefixSegmentAccumulator: item.ConsumedTailPrefixSegmentAccumulator, ConsumedTailPrefixMutationCount: item.ConsumedTailPrefixMutationCount, ConsumedTailPrefixMutationAccumulator: item.ConsumedTailPrefixMutationAccumulator, RetainedTailSuffixFromSequenceExclusive: item.RetainedTailSuffixFromSequenceExclusive, RetainedTailSuffixThroughSequence: item.RetainedTailSuffixThroughSequence, RetainedTailSuffixSourceAccumulator: item.RetainedTailSuffixSourceRangeAccumulator, RetainedTailSuffixSegmentCount: item.RetainedTailSuffixSegmentCount, RetainedTailSuffixSegmentAccumulator: item.RetainedTailSuffixSegmentAccumulator, RetainedTailSuffixMutationCount: item.RetainedTailSuffixMutationCount, RetainedTailSuffixMutationAccumulator: item.RetainedTailSuffixMutationAccumulator, CheckpointConfirmationFingerprint: item.CheckpointFullConfirmationFingerprint, Fingerprint: item.FrameFingerprint}
			switch transition := item.ResidentTransition.Transition.(type) {
			case *protocol.PresentationHistoryRootResidentTransition_Unchanged:
				if transition.Unchanged.BeforeResidentVectorFingerprint != transition.Unchanged.AfterResidentVectorFingerprint || !validFingerprint(transition.Unchanged.ExactEquivalenceProofFingerprint) || !validFingerprint(transition.Unchanged.TransitionFingerprint) {
					return ObservationResult{}, errors.New("terminal unchanged resident proof is invalid")
				}
				advance.TransitionKind, advance.BeforeResidentFingerprint, advance.AfterResidentFingerprint, advance.TransitionProofFingerprint = ResidentTransitionUnchanged, transition.Unchanged.BeforeResidentVectorFingerprint, transition.Unchanged.AfterResidentVectorFingerprint, transition.Unchanged.TransitionFingerprint
			case *protocol.PresentationHistoryRootResidentTransition_BoundedChanges:
				if transition.BoundedChanges.ChangeCount != uint64(len(transition.BoundedChanges.OrderedChanges)) || transition.BoundedChanges.ChangeCount == 0 || transition.BoundedChanges.EncodedChangeBytes == 0 || !validFingerprint(transition.BoundedChanges.TransitionLimitsPolicyFingerprint) || !validFingerprint(transition.BoundedChanges.OrderedChangeAccumulator) || !validFingerprint(transition.BoundedChanges.TransitionFingerprint) {
					return ObservationResult{}, errors.New("terminal bounded resident proof is invalid")
				}
				advance.TransitionKind, advance.BeforeResidentFingerprint, advance.AfterResidentFingerprint, advance.TransitionProofFingerprint = ResidentTransitionBoundedChanges, transition.BoundedChanges.BeforeResidentVectorFingerprint, transition.BoundedChanges.AfterResidentVectorFingerprint, transition.BoundedChanges.TransitionFingerprint
				for _, raw := range transition.BoundedChanges.OrderedChanges {
					wrapped := &protocol.HistoryEntryChange{}
					switch change := raw.Change.(type) {
					case *protocol.PresentationHistoryResidentChange_Upsert:
						wrapped.Change = &protocol.HistoryEntryChange_Upsert{Upsert: &protocol.HistoryEntryUpsert{HistoryEntryId: change.Upsert.HistoryEntryId, PlacementKey: change.Upsert.PlacementKey, ExpectedPreviousEntryFingerprint: change.Upsert.ExpectedPreviousEntryFingerprint, ResultingRankedEntry: change.Upsert.ResultingRankedEntry, ChangeFingerprint: change.Upsert.ChangeFingerprint}}
					case *protocol.PresentationHistoryResidentChange_Remove:
						wrapped.Change = &protocol.HistoryEntryChange_Remove{Remove: &protocol.HistoryEntryRemove{HistoryEntryId: change.Remove.HistoryEntryId, PlacementKey: change.Remove.PlacementKey, ExpectedPreviousEntryFingerprint: change.Remove.ExpectedPreviousEntryFingerprint, ChangeFingerprint: change.Remove.ChangeFingerprint}}
					}
					parsed, err := historyChangeFromProto(wrapped)
					if err != nil {
						return ObservationResult{}, err
					}
					advance.Changes = append(advance.Changes, parsed)
				}
			case *protocol.PresentationHistoryRootResidentTransition_RebaseRequired:
				if transition.RebaseRequired.TargetRootIdentity == nil || transition.RebaseRequired.TargetRootIdentity.RootIdentityFingerprint != resulting.RootFingerprint || transition.RebaseRequired.TargetActiveHeadFingerprint != head.Fingerprint || transition.RebaseRequired.StableReason == "" || transition.RebaseRequired.BoundedRebaseOrSnapshotToken == "" || transition.RebaseRequired.TokenGeneration == 0 || transition.RebaseRequired.ExpiresAtUtc == "" || !validFingerprint(transition.RebaseRequired.TransitionFingerprint) {
					return ObservationResult{}, errors.New("terminal resident rebase proof is invalid")
				}
				advance.TransitionKind, advance.BeforeResidentFingerprint, advance.TransitionProofFingerprint = ResidentTransitionRebaseRequired, transition.RebaseRequired.BeforeResidentVectorFingerprint, transition.RebaseRequired.TransitionFingerprint
			default:
				return ObservationResult{}, errors.New("terminal resident transition is unknown")
			}
			result.RootAdvance = advance
		case *protocol.DurableObservationBranch_Gap:
			item := branch.Gap
			if item.RequestId != batch.RequestId || item.GapReason == protocol.ObservationGapReason_OBSERVATION_GAP_REASON_UNSPECIFIED || !validFingerprint(item.FrameFingerprint) {
				return ObservationResult{}, errors.New("terminal durable gap is invalid")
			}
			result.DurableGap = &DurableGap{RequestID: item.RequestId, LatestAuthorityHighWater: item.LatestAuthorityHighWater, LatestProjectionRevision: item.LatestProjectionRevision, Reason: item.GapReason, Fingerprint: item.FrameFingerprint}
		default:
			return ObservationResult{}, errors.New("terminal durable observation branch is unknown")
		}
	}
	if batch.Operational != nil {
		present++
		if delta := batch.Operational.GetDelta(); delta != nil {
			if delta.RequestId != batch.RequestId || delta.OperationalGeneration == 0 || !validFingerprint(delta.FrameFingerprint) {
				return ObservationResult{}, errors.New("terminal operational delta is invalid")
			}
			if err := protocol.ValidateFingerprint("terminal-operational-delta-frame:v1", delta, "frame_fingerprint", delta.FrameFingerprint); err != nil {
				return ObservationResult{}, err
			}
			changes := make([]OperationalChange, 0, len(delta.OrderedChanges))
			expected := uint64(0)
			for _, raw := range delta.OrderedChanges {
				change, err := operationalChangeFromProto(raw)
				if err != nil {
					return ObservationResult{}, err
				}
				if change.Generation != delta.OperationalGeneration || (expected != 0 && change.Cursor != expected+1) {
					return ObservationResult{}, errors.New("terminal operational changes are discontinuous")
				}
				expected = change.Cursor
				changes = append(changes, change)
			}
			if len(changes) == 0 || expected != delta.OperationalCursor {
				return ObservationResult{}, errors.New("terminal operational delta is empty or stale")
			}
			result.OperationalDelta = &OperationalDelta{RequestID: delta.RequestId, Generation: delta.OperationalGeneration, Cursor: delta.OperationalCursor, Changes: changes, Fingerprint: delta.FrameFingerprint}
		} else if gap := batch.Operational.GetGap(); gap != nil {
			if gap.RequestId != batch.RequestId || gap.LatestOperationalGeneration == 0 || gap.GapReason == protocol.ObservationGapReason_OBSERVATION_GAP_REASON_UNSPECIFIED || !validFingerprint(gap.FrameFingerprint) {
				return ObservationResult{}, errors.New("terminal operational gap is invalid")
			}
			result.OperationalGap = &OperationalGap{RequestID: gap.RequestId, LatestGeneration: gap.LatestOperationalGeneration, LatestCursor: gap.LatestOperationalCursor, Reason: gap.GapReason, Fingerprint: gap.FrameFingerprint}
		} else {
			return ObservationResult{}, errors.New("terminal operational observation branch is unknown")
		}
	}
	if present != batch.IncludedPlaneCount {
		return ObservationResult{}, errors.New("terminal observation plane count mismatch")
	}
	return ObservationResult{Batch: result, IsBatch: true}, nil
}

func HistoryPageFromProto(value *protocol.HistoryPageResponse) (HistoryPageResult, error) {
	if value == nil {
		return HistoryPageResult{}, errors.New("terminal history page response is empty")
	}
	switch branch := value.Outcome.(type) {
	case *protocol.HistoryPageResponse_Page:
		item := branch.Page
		if item == nil || item.RequestId == "" || item.ValidatedInputCursorFingerprint == "" || item.ValidatedRequestDirection == protocol.HistoryPageRequest_DIRECTION_UNSPECIFIED || !validFingerprint(item.ResponseFingerprint) {
			return HistoryPageResult{}, errors.New("terminal history page data is incomplete")
		}
		root, err := rootFromProto(item.ValidatedRootIdentity)
		if err != nil {
			return HistoryPageResult{}, err
		}
		if !validFingerprint(item.OrderedHistoryEntryAccumulator) || !validFingerprint(item.ContinuityProofFingerprint) {
			return HistoryPageResult{}, errors.New("terminal history page proof is incomplete")
		}
		result := HistoryPageResult{Kind: HistoryPageDataKind, RequestID: item.RequestId, RequestedCursorFingerprint: item.ValidatedInputCursorFingerprint, Direction: item.ValidatedRequestDirection, Root: root, HasMoreBefore: item.HasMoreBefore, HasMoreAfter: item.HasMoreAfter, OrderedEntryAccumulator: item.OrderedHistoryEntryAccumulator, ContinuityProofFingerprint: item.ContinuityProofFingerprint, Fingerprint: item.ResponseFingerprint}
		seen := map[string]bool{}
		var previousRank uint64
		for _, raw := range item.OrderedHistoryEntries {
			encoded, marshalErr := (proto.MarshalOptions{Deterministic: true}).Marshal(raw)
			if marshalErr != nil || uint64(len(encoded)) > ^uint64(0)-result.decodedCarrierBytes {
				return HistoryPageResult{}, errors.New("terminal history page carrier accounting failed")
			}
			cell, err := historyCellFromRanked(raw)
			if err != nil || seen[cell.ID] || (len(result.Entries) > 0 && cell.DisplayRank <= previousRank) {
				return HistoryPageResult{}, errors.New("terminal history page entry is invalid")
			}
			seen[cell.ID] = true
			previousRank = cell.DisplayRank
			result.Entries = append(result.Entries, cell)
			result.decodedCarrierBytes += uint64(len(encoded))
		}
		if item.BeforeCursor != nil {
			result.BeforeCursor, err = cursorFromProto(item.BeforeCursor)
			if err != nil {
				return HistoryPageResult{}, err
			}
			result.HasBeforeCursor = true
		}
		if item.AfterCursor != nil {
			result.AfterCursor, err = cursorFromProto(item.AfterCursor)
			if err != nil {
				return HistoryPageResult{}, err
			}
			result.HasAfterCursor = true
		}
		if (result.HasBeforeCursor && result.BeforeCursor.Root != root) ||
			(result.HasAfterCursor && result.AfterCursor.Root != root) ||
			(len(result.Entries) == 0 && ((result.Direction == HistoryPageBefore && result.HasMoreBefore) ||
				(result.Direction == HistoryPageAfter && result.HasMoreAfter))) {
			return HistoryPageResult{}, errors.New("terminal history page continuation is invalid")
		}
		return result, nil
	case *protocol.HistoryPageResponse_Stale:
		item := branch.Stale
		if item == nil || item.RequestId == "" || item.RequestedCursorFingerprint == "" || !validFingerprint(item.ResponseFingerprint) {
			return HistoryPageResult{}, errors.New("terminal stale history response is incomplete")
		}
		root, err := rootFromProto(item.LatestRootIdentity)
		if err != nil {
			return HistoryPageResult{}, err
		}
		result := HistoryPageResult{Kind: HistoryPageCursorStale, RequestID: item.RequestId, RequestedCursorFingerprint: item.RequestedCursorFingerprint, Root: root, Fingerprint: item.ResponseFingerprint}
		if item.ReplacementCursor != nil {
			result.ReplacementCursor, err = cursorFromProto(item.ReplacementCursor)
			if err != nil || item.ReplacementCursorAnchorProofFingerprint == nil || !validFingerprint(*item.ReplacementCursorAnchorProofFingerprint) {
				return HistoryPageResult{}, errors.New("terminal stale replacement proof is incomplete")
			}
			result.HasReplacementCursor = true
			result.ReplacementProofFingerprint = *item.ReplacementCursorAnchorProofFingerprint
		} else if item.ReplacementCursorAnchorProofFingerprint != nil {
			return HistoryPageResult{}, errors.New("terminal stale replacement proof is partial")
		}
		return result, nil
	case *protocol.HistoryPageResponse_Rebase:
		item := branch.Rebase
		if item == nil || item.RequestId == "" || item.RequestedCursorFingerprint == "" || !validFingerprint(item.ResponseFingerprint) {
			return HistoryPageResult{}, errors.New("terminal history rebase response is incomplete")
		}
		root, err := rootFromProto(item.LatestRootIdentity)
		if err != nil {
			return HistoryPageResult{}, err
		}
		return HistoryPageResult{Kind: HistoryPageRebaseRequired, RequestID: item.RequestId, RequestedCursorFingerprint: item.RequestedCursorFingerprint, Root: root, Fingerprint: item.ResponseFingerprint}, nil
	case *protocol.HistoryPageResponse_Reconciliation:
		item := branch.Reconciliation
		if item == nil || item.RequestId == "" || item.RequestedCursorFingerprint == "" || item.FaultCode == "" || item.ReconciliationOwnerIdentity == "" || !validFingerprint(item.ResponseFingerprint) {
			return HistoryPageResult{}, errors.New("terminal history reconciliation response is incomplete")
		}
		result := HistoryPageResult{Kind: HistoryPageReconciliationRequired, RequestID: item.RequestId, RequestedCursorFingerprint: item.RequestedCursorFingerprint, FaultCode: item.FaultCode, ReconciliationOwnerIdentity: item.ReconciliationOwnerIdentity, Fingerprint: item.ResponseFingerprint}
		if item.RetryAfterMs != nil {
			result.HasRetryAfter = true
			result.RetryAfterMS = *item.RetryAfterMs
		}
		return result, nil
	default:
		return HistoryPageResult{}, errors.New("terminal history page branch is unknown")
	}
}

func validControlSections(values []protocol.TerminalControlSectionKind) bool {
	if len(values) == 0 || len(values) > 5 {
		return false
	}
	previous := protocol.TerminalControlSectionKind_TERMINAL_CONTROL_SECTION_KIND_UNSPECIFIED
	for _, value := range values {
		if value <= protocol.TerminalControlSectionKind_TERMINAL_CONTROL_SECTION_KIND_UNSPECIFIED || value > protocol.TerminalControlSectionKind_CONTROL_NOTIFICATIONS || value <= previous {
			return false
		}
		previous = value
	}
	return true
}

func ProjectionSnapshotOutcomeFromProto(value *protocol.ProjectionSnapshotResponse) (ProjectionSnapshotOutcome, error) {
	if value == nil {
		return ProjectionSnapshotOutcome{}, errors.New("terminal projection snapshot response is empty")
	}
	if snapshot := value.GetSnapshot(); snapshot != nil {
		parsed, err := DurableSnapshotFromWire(snapshot)
		if err != nil {
			return ProjectionSnapshotOutcome{}, err
		}
		return ProjectionSnapshotOutcome{Snapshot: parsed}, nil
	}
	rebase := value.GetControlRebaseRequired()
	if rebase == nil || rebase.RequestId == "" || rebase.RequestedMinimumControlCursorFingerprint == "" || rebase.StableReason != protocol.ProjectionSnapshotControlRebaseRequired_CONTROL_GENERATION_REBASED || !validFingerprint(rebase.ResponseFingerprint) {
		return ProjectionSnapshotOutcome{}, errors.New("terminal projection snapshot outcome is unknown")
	}
	if err := protocol.ValidateFingerprint("terminal-projection-snapshot-control-rebase:v1", rebase, "response_fingerprint", rebase.ResponseFingerprint); err != nil {
		return ProjectionSnapshotOutcome{}, err
	}
	cursor, err := controlCursorFromProto(rebase.LatestControlCursor)
	if err != nil {
		return ProjectionSnapshotOutcome{}, err
	}
	return ProjectionSnapshotOutcome{RebaseRequired: true, RequestedMinimumFingerprint: rebase.RequestedMinimumControlCursorFingerprint, LatestControlCursor: cursor, Fingerprint: rebase.ResponseFingerprint}, nil
}

func validFingerprint(value string) bool {
	return len(value) == len("sha256:")+64 && strings.HasPrefix(value, "sha256:")
}

func validKeyedCommitment(value string) bool {
	return len(value) == len("hmac-sha256:")+64 && strings.HasPrefix(value, "hmac-sha256:")
}

func (value HistoryCursor) String() string {
	return fmt.Sprintf("%s@%s", value.Fingerprint, value.Root.RootFingerprint)
}
