// Code generated by generate_terminal_protocol_contract.py. DO NOT EDIT.
package protocolvalue

import "github.com/plumliu/pulsara-agent/clients/terminal/internal/protocol"

var S3SupportedCapabilities = append(
	append([]protocol.TerminalClientCapability(nil), S2SupportedCapabilities...),
	protocol.TerminalClientCapability_CONTROLLER_COMMAND_V1,
	protocol.TerminalClientCapability_COMMAND_QUERY_V1,
)

var S3RequiredCapabilities = append([]protocol.TerminalClientCapability(nil), S3SupportedCapabilities...)
