// Code generated by generate_terminal_protocol_contract.py. DO NOT EDIT.
package protocolvalue

import "github.com/plumliu/pulsara-agent/clients/terminal/internal/protocol"

const (
	ProtocolMajor     uint32 = 2
	ProtocolMinor     uint32 = 0
	SchemaFingerprint        = "sha256:61c53a72b867a1f10794959e0b27244833ca5488a965550b1881f252a22004e6"

	MaximumFrameBytes                  uint32 = 8 * 1024 * 1024
	MaximumHistoryPageCells            uint32 = 256
	MaximumHistoryPageDecodedBytes     uint32 = 4 * 1024 * 1024
	MaximumPinnedHistoryRoots          uint32 = 4
	MaximumObservationWaitMS           uint32 = 5_000
	SecretFrameMaximumBytes            uint32 = 64 * 1024
	MaximumDurableObservationBytes     uint32 = 4 * 1024 * 1024
	MaximumControlObservationBytes     uint32 = 256 * 1024
	MaximumObservationBatchBytes       uint32 = 6 * 1024 * 1024
	OperationalContractFingerprint            = "sha256:0c7eb70336d2d19f34792ff5edf00867aeb2d0337201f4a1dcbb94e81eb4a71d"
	ControlRegistryContractFingerprint        = "sha256:969a252c5618649a74bac9cc49b191f1556de44dd855f0de4f2a06c0e919442c"
	ActiveQueueContractFingerprint            = "sha256:c9f5bdf1b2e641b337a9d598023ba50bc7bb1764f46cda0665664c6c8f46bae2"
)

var S1SupportedCapabilities = []protocol.TerminalClientCapability{
	protocol.TerminalClientCapability_PRESENTATION_SNAPSHOT_V1,
	protocol.TerminalClientCapability_OPERATIONAL_SNAPSHOT_V1,
	protocol.TerminalClientCapability_BOOTSTRAP_CARRIER_V1,
	protocol.TerminalClientCapability_LAUNCH_AUTH_PREFACE_V1,
	protocol.TerminalClientCapability_ATTACH_ACK_V1,
}

var S1RequiredCapabilities = append([]protocol.TerminalClientCapability(nil), S1SupportedCapabilities...)

const TransportAuthAckResultRecovery = protocol.TransportAuthDisposition_TRANSPORT_ACK_RESULT_RECOVERY

// CanonicalClientFingerprint exposes the Protocol-owned canonical JSON helper
// without allowing application packages to import generated Protobuf types.
func CanonicalClientFingerprint(namespace string, value any) (string, error) {
	return protocol.CanonicalJSONFingerprint(namespace, value)
}

func WireOperationIdentity(clientInstanceID string, appGeneration, connectionGeneration, operationGeneration uint64, kind uint8) (string, string, error) {
	operationFingerprint, err := protocol.CanonicalJSONFingerprint("terminal-client-operation-id:v1", map[string]any{
		"client_instance_id":    clientInstanceID,
		"app_generation":        appGeneration,
		"connection_generation": connectionGeneration,
		"operation_generation":  operationGeneration,
		"operation_kind":        kind,
	})
	if err != nil {
		return "", "", err
	}
	operationID := "terminal-operation:" + operationFingerprint[len("sha256:"):]
	requestFingerprint, err := protocol.CanonicalJSONFingerprint("terminal-client-request-id:v1", map[string]any{
		"operation_id":   operationID,
		"operation_kind": kind,
	})
	if err != nil {
		return "", "", err
	}
	return operationID, "terminal-request:" + requestFingerprint[len("sha256:"):], nil
}

func LocalOperationIdentity(clientInstanceID string, appGeneration, operationGeneration uint64, kind uint8) (string, error) {
	fingerprint, err := protocol.CanonicalJSONFingerprint("terminal-client-local-operation-id:v1", map[string]any{
		"client_instance_id":   clientInstanceID,
		"app_generation":       appGeneration,
		"operation_generation": operationGeneration,
		"operation_kind":       kind,
	})
	if err != nil {
		return "", err
	}
	return "terminal-local-operation:" + fingerprint[len("sha256:"):], nil
}

type HeartbeatLivenessDisposition = protocol.HeartbeatLivenessDisposition

const (
	HeartbeatLivenessUnspecified = protocol.HeartbeatLivenessDisposition_HEARTBEAT_LIVENESS_DISPOSITION_UNSPECIFIED
	HeartbeatLeaseRenewed        = protocol.HeartbeatLivenessDisposition_ATTACHMENT_ACTIVE_LEASE_RENEWED
	HeartbeatSessionClosing      = protocol.HeartbeatLivenessDisposition_SESSION_CLOSING_LEASE_NOT_RENEWED
)
