"""Process-local provider stream circuit breakers."""

MAX_COMPLETED_PROVIDER_RESPONSE_AGGREGATE_BYTES = 16 * 1024 * 1024
MAX_CHAT_REASONING_REPLAY_AGGREGATE_BYTES = (
    MAX_COMPLETED_PROVIDER_RESPONSE_AGGREGATE_BYTES
)
MAX_PROVIDER_DECODED_JSON_NODES = 65_536
MAX_PROVIDER_DECODED_JSON_DEPTH = 128
MAX_PROVIDER_DECODED_JSON_STRING_BYTES = 16 * 1024 * 1024

__all__ = [
    "MAX_COMPLETED_PROVIDER_RESPONSE_AGGREGATE_BYTES",
    "MAX_CHAT_REASONING_REPLAY_AGGREGATE_BYTES",
    "MAX_PROVIDER_DECODED_JSON_DEPTH",
    "MAX_PROVIDER_DECODED_JSON_NODES",
    "MAX_PROVIDER_DECODED_JSON_STRING_BYTES",
]
