"""Process-local provider stream circuit breakers."""

MAX_TRANSPORT_SOURCE_ITEMS_PER_MODEL_CALL = 16_384
MAX_SANITIZED_SOURCE_PAYLOAD_BYTES_PER_MODEL_CALL = 16 * 1024 * 1024

__all__ = [
    "MAX_SANITIZED_SOURCE_PAYLOAD_BYTES_PER_MODEL_CALL",
    "MAX_TRANSPORT_SOURCE_ITEMS_PER_MODEL_CALL",
]
