"""Process-local provider stream circuit breakers."""

MAX_TRANSPORT_SOURCE_ITEMS_PER_MODEL_CALL = 16_384
MAX_SANITIZED_SOURCE_PAYLOAD_BYTES_PER_MODEL_CALL = 16 * 1024 * 1024
MAX_COMPLETED_PROVIDER_RESPONSE_AGGREGATE_BYTES = 16 * 1024 * 1024
MAX_PROVIDER_DECODED_JSON_NODES = 65_536
MAX_PROVIDER_DECODED_JSON_DEPTH = 128
MAX_PROVIDER_DECODED_JSON_STRING_BYTES = 16 * 1024 * 1024

__all__ = [
    "MAX_COMPLETED_PROVIDER_RESPONSE_AGGREGATE_BYTES",
    "MAX_PROVIDER_DECODED_JSON_DEPTH",
    "MAX_PROVIDER_DECODED_JSON_NODES",
    "MAX_PROVIDER_DECODED_JSON_STRING_BYTES",
    "MAX_SANITIZED_SOURCE_PAYLOAD_BYTES_PER_MODEL_CALL",
    "MAX_TRANSPORT_SOURCE_ITEMS_PER_MODEL_CALL",
]
