"""Low-level contract facade with lazy compatibility exports.

Focused primitive modules are safe dependency leaves.  The package facade
must not eagerly aggregate the legacy authority/projection vocabulary when
the Stage 2 kernel imports one such leaf.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_LAZY_MODULES = (
    "pulsara_agent.primitives.authority_materialization",
    "pulsara_agent.primitives.context",
    "pulsara_agent.primitives.context_source",
    "pulsara_agent.primitives.context_input_commit",
    "pulsara_agent.primitives.model_call",
    "pulsara_agent.primitives.permission",
    "pulsara_agent.primitives.frozen",
    "pulsara_agent.primitives.run_entry",
    "pulsara_agent.primitives.run_lifecycle",
    "pulsara_agent.primitives.tool_observation",
    "pulsara_agent.primitives.terminal_projection",
    "pulsara_agent.primitives.tool_result",
)


def __getattr__(name: str) -> Any:
    if name not in __all__:
        raise AttributeError(name)
    for module_name in _LAZY_MODULES:
        module = import_module(module_name)
        try:
            value = getattr(module, name)
        except AttributeError:
            continue
        globals()[name] = value
        return value
    raise AttributeError(name)


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))

__all__ = [
    "ActivePhysicalReservationStateFact",
    "AuthorityMaterializationLimits",
    "CompactionTargetEstimateFact",
    "CompactionObservedAfterMeasurementFact",
    "CapabilityExposureOwnerFact",
    "CapabilityExposureOwnerKind",
    "CapabilityResultRenderContractFact",
    "CapabilityResultRenderVariantFact",
    "CanonicalToolResultBlockFact",
    "CanonicalToolResultBlockSemanticFact",
    "CanonicalToolResultContentBlockFact",
    "CanonicalToolResultDataBlockSemanticFact",
    "CanonicalToolResultTextBlockSemanticFact",
    "CheckpointDispatchBarrierFact",
    "CheckpointProjectionBaseReferenceFact",
    "ContextBudgetReportEvent",
    "ContextAuthoritySlicePlan",
    "ContextCandidateSourceSelectionFact",
    "ContextCandidateCollectionPolicyFact",
    "ContextCompilePolicyFact",
    "ContextCompileFailureStage",
    "ContextCompileInputCommitFact",
    "ContextCompileSourceReferenceSetFact",
    "ContextEventRangeFact",
    "ContextEventReferenceFact",
    "ContextFactSnapshotFact",
    "ContextInputIdentityFact",
    "ContextInputAuditExpectationFact",
    "LongHorizonContextAttributionFact",
    "ContextSectionCandidate",
    "ContextSourceCandidateAttributionFact",
    "ContextSourceCandidateSemanticFact",
    "ContextSourceContractFact",
    "ContextSourceId",
    "CurrentUserMessageFact",
    "DataMediaTypeNormalizationContractFact",
    "DataMediaTypeNormalizationRuleFact",
    "DURABLE_FACT_FINGERPRINT_REGISTRY",
    "DEFAULT_PERMISSION_MODE",
    "DurableRunExistence",
    "DurableFactFingerprintRegistry",
    "DurableFactFingerprintSpec",
    "DurableFingerprintJoinSpec",
    "ExternalToolCallRequirementFact",
    "FixedBatchBurstContractFact",
    "FixedBatchEventContractFact",
    "FrozenFactBase",
    "FrozenRuntimeStateBase",
    "FrozenJsonArrayFact",
    "FrozenJsonObjectFact",
    "HostRunBoundaryIdentityFact",
    "HostRunBoundaryKind",
    "LedgerMaterializationAccountStateFact",
    "LedgerMaterializationConsumerHorizonFact",
    "LedgerMaterializationConsumerKind",
    "LedgerMaterializationGenerationFact",
    "LedgerWriteAdmissionClass",
    "ModelCallDiagnosticFact",
    "ModelCallSemanticSourceFact",
    "ModelCallTerminalProjectionEndReferenceFact",
    "ModelCallPurpose",
    "ModelContextLimits",
    "ModelContextMode",
    "ModelDataBlockSemanticFact",
    "ModelProjectionItemFact",
    "ModelProviderErrorSemanticFact",
    "ModelTerminalProjectionPayloadFact",
    "ModelTerminalProjectionSemanticFact",
    "ModelTextBlockSemanticFact",
    "ModelThinkingBlockSemanticFact",
    "ModelToolCallBlockSemanticFact",
    "ModelTokenUsageFact",
    "NonTranscriptEventContractFact",
    "PermissionMode",
    "PreparedContextCandidateSet",
    "PreparedRuntimeValueBase",
    "ProjectedToolResultCompileRefFact",
    "PreparedToolResultRenderInput",
    "PresetPermissionPolicyFact",
    "PhysicalBookkeepingEventBoundFact",
    "PhysicalBurstContractFact",
    "PhysicalChargeContractFact",
    "PhysicalOperationKind",
    "PhysicalOperationReservationFact",
    "PhysicalStoredEnvelopeObservation",
    "ResolvedModelCallFact",
    "ResolvedModelContextBudgetFact",
    "ResolvedModelOptionsFact",
    "ResolvedModelTargetFact",
    "ResolvedToolResultRenderPolicyFact",
    "RunPermissionSnapshotFact",
    "RunSeedProjectionBaseReferenceFact",
    "RunEntryKind",
    "RunStopReason",
    "RunTerminalizationKind",
    "SubagentRunEntryFact",
    "TerminalArtifactContentReferenceFact",
    "TerminalContentArtifactCodecContractFact",
    "TerminalContentCanonicalizationContractFact",
    "TerminalContentSemanticFact",
    "TerminalInlineContentFact",
    "TerminalProjectionDocumentContractFact",
    "TerminalProjectionDocumentFact",
    "TerminalProjectionReferenceFact",
    "StableEventIdentityFact",
    "StoredEnvelopeIdentityBoundsFact",
    "TokenEstimatorFact",
    "ToolObservationTimingFact",
    "ToolResultEssentialCapturePolicyFact",
    "ToolResultExecutionSemanticsFact",
    "ToolResultRenderPolicyBasisFact",
    "ToolResultRenderProfileFact",
    "ToolResultRenderUnit",
    "ToolResultSemanticSourceFact",
    "ToolResultTerminalProjectionEndReferenceFact",
    "ToolResultSemanticsBuilderContractFact",
    "ToolResultStateFact",
    "ToolTerminalProjectionPayloadFact",
    "ToolTerminalProjectionSemanticFact",
    "ToolDeltaBurstContractFact",
    "TranscriptDomainPrefixFact",
    "TranscriptDomainSparseReadProofFact",
    "TranscriptAccelerationEventContractFact",
    "TranscriptCompileInput",
    "TranscriptEventDomainRegistryContractFact",
    "TranscriptProjectionLiveAssemblyState",
    "TranscriptProjectionBaseReferenceFact",
    "TranscriptProjectionStableSemanticStateFact",
    "TranscriptProjectionWindowFact",
    "TranscriptSemanticEventContractFact",
    "TransportSegmentedBurstContractFact",
    "canonical_json_bytes",
    "canonical_utc_timestamp",
    "build_context_input_audit_expectation",
    "context_fingerprint",
    "build_frozen_fact",
    "freeze_json",
    "parse_permission_mode",
    "preset_permission_payload",
    "preset_permission_policy_fact",
    "sha256_fingerprint",
    "thaw_json",
]
