"""Single immutable identity for presentation-history placement encoding."""

PRESENTATION_PLACEMENT_KEY_CONTRACT_ID = "pulsara.presentation-history-placement-key"
PRESENTATION_PLACEMENT_KEY_CONTRACT_VERSION = "1"
PRESENTATION_PLACEMENT_KEY_CONTRACT_FINGERPRINT = (
    "sha256:a6c538dba46fb9e3a7f0dbb210ea20cf33322d7a1a55402b9ae25f294baf96ad"
)


__all__ = [
    "PRESENTATION_PLACEMENT_KEY_CONTRACT_FINGERPRINT",
    "PRESENTATION_PLACEMENT_KEY_CONTRACT_ID",
    "PRESENTATION_PLACEMENT_KEY_CONTRACT_VERSION",
]
