"""MCP runtime support."""

from pulsara_agent.runtime.mcp.manager import McpClientManager, MockMcpClientManager
from pulsara_agent.runtime.mcp.sdk import SdkMcpClientManager, SdkMcpConnection, discover_mcp_server
from pulsara_agent.runtime.mcp.supervisor import McpServerSupervisor
from pulsara_agent.runtime.mcp.types import (
    McpBindingIdentity,
    McpContentArtifact,
    McpDiscoveredTool,
    McpDiscoveredPrompt,
    McpDiscoveredResource,
    McpDiscoveredResourceTemplate,
    McpInputRequestDTO,
    McpInputRequired,
    McpInputRequiredResolution,
    McpOriginalRequest,
    McpRequestSourceMethod,
    McpRequiredStartupError,
    McpServerConfig,
    McpServerSnapshot,
    McpServerStatus,
    McpServerTransportKind,
    McpStdioConfig,
    McpStreamableHttpConfig,
    McpToolAnnotations,
    McpToolResult,
    McpInstalledCapabilitySnapshot,
    mangle_mcp_tool_name,
)

__all__ = [
    "McpBindingIdentity",
    "McpContentArtifact",
    "McpClientManager",
    "McpDiscoveredPrompt",
    "McpDiscoveredResource",
    "McpDiscoveredResourceTemplate",
    "McpDiscoveredTool",
    "McpInputRequestDTO",
    "McpInputRequired",
    "McpInputRequiredResolution",
    "McpOriginalRequest",
    "McpRequestSourceMethod",
    "McpRequiredStartupError",
    "McpServerConfig",
    "McpServerSnapshot",
    "McpServerStatus",
    "McpServerTransportKind",
    "McpStdioConfig",
    "McpStreamableHttpConfig",
    "McpToolAnnotations",
    "McpToolResult",
    "MockMcpClientManager",
    "McpInstalledCapabilitySnapshot",
    "McpServerSupervisor",
    "SdkMcpClientManager",
    "SdkMcpConnection",
    "discover_mcp_server",
    "mangle_mcp_tool_name",
]
