// Code generated by generate_terminal_protocol_contract.py. DO NOT EDIT.
package protocol

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func Fingerprint(namespace string, message proto.Message, ownField string, clearFields ...string) (string, error) {
	if namespace == "" || strings.ContainsRune(namespace, 0) || message == nil {
		return "", errors.New("invalid terminal fingerprint input")
	}
	clone := proto.Clone(message)
	reflection := clone.ProtoReflect()
	for _, name := range append([]string{ownField}, clearFields...) {
		field := reflection.Descriptor().Fields().ByName(protoreflect.Name(name))
		if field == nil {
			return "", fmt.Errorf("unknown terminal fingerprint field %q", name)
		}
		reflection.Clear(field)
	}
	payload, err := proto.MarshalOptions{Deterministic: true}.Marshal(clone)
	if err != nil {
		return "", err
	}
	digest := sha256.New()
	digest.Write([]byte(namespace))
	digest.Write([]byte{0})
	digest.Write(payload)
	return "sha256:" + hex.EncodeToString(digest.Sum(nil)), nil
}

func ValidateFingerprint(namespace string, message proto.Message, ownField string, observed string, clearFields ...string) error {
	expected, err := Fingerprint(namespace, message, ownField, clearFields...)
	if err != nil {
		return err
	}
	if observed != expected {
		return fmt.Errorf("terminal %s mismatch", ownField)
	}
	return nil
}

// ValidateFingerprintFormats rejects malformed opaque and recomputable
// fingerprint carriers before a generated DTO-specific validator runs.
func ValidateFingerprintFormats(message proto.Message) error {
	if message == nil {
		return errors.New("nil terminal protobuf fingerprint carrier")
	}
	return validateFingerprintMessage(message.ProtoReflect())
}

func validateFingerprintMessage(message protoreflect.Message) error {
	fields := message.Descriptor().Fields()
	for index := 0; index < fields.Len(); index++ {
		field := fields.Get(index)
		if strings.Contains(string(field.Name()), "fingerprint") && field.Kind() == protoreflect.StringKind {
			if field.IsList() {
				values := message.Get(field).List()
				for item := 0; item < values.Len(); item++ {
					if value := values.Get(item).String(); value != "" && !validSHA256Fingerprint(value) {
						return fmt.Errorf("terminal %s.%s[%d] is not a SHA-256 fingerprint", message.Descriptor().Name(), field.Name(), item)
					}
				}
			} else if value := message.Get(field).String(); value != "" && !validSHA256Fingerprint(value) {
				return fmt.Errorf("terminal %s.%s is not a SHA-256 fingerprint", message.Descriptor().Name(), field.Name())
			}
		}
		if field.Kind() != protoreflect.MessageKind && field.Kind() != protoreflect.GroupKind {
			continue
		}
		if field.IsList() {
			values := message.Get(field).List()
			for item := 0; item < values.Len(); item++ {
				if err := validateFingerprintMessage(values.Get(item).Message()); err != nil {
					return err
				}
			}
		} else if message.Has(field) {
			if err := validateFingerprintMessage(message.Get(field).Message()); err != nil {
				return err
			}
		}
	}
	return nil
}

func validSHA256Fingerprint(value string) bool {
	if len(value) != len("sha256:")+sha256.Size*2 || !strings.HasPrefix(value, "sha256:") {
		return false
	}
	_, err := hex.DecodeString(value[len("sha256:"):])
	return err == nil && value == strings.ToLower(value)
}

func InstallFingerprint(namespace string, message proto.Message, ownField string, clearFields ...string) (string, error) {
	value, err := Fingerprint(namespace, message, ownField, clearFields...)
	if err != nil {
		return "", err
	}
	reflection := message.ProtoReflect()
	field := reflection.Descriptor().Fields().ByName(protoreflect.Name(ownField))
	if field == nil || field.Kind() != protoreflect.StringKind {
		return "", fmt.Errorf("invalid terminal own fingerprint field %q", ownField)
	}
	reflection.Set(field, protoreflect.ValueOfString(value))
	return value, nil
}

func AttachmentChallengeCommitment(authAttemptID, candidateFingerprint, candidateID, connectionID, winnerFingerprint, requestID string, challenge []byte) (string, error) {
	if len(challenge) != 32 {
		return "", errors.New("terminal attachment challenge must contain 32 bytes")
	}
	values := map[string]string{
		"auth_attempt_id":                authAttemptID,
		"candidate_fingerprint":          candidateFingerprint,
		"candidate_id":                   candidateID,
		"connection_id":                  connectionID,
		"negotiation_winner_fingerprint": winnerFingerprint,
		"request_id":                     requestID,
	}
	for _, value := range values {
		if value == "" {
			return "", errors.New("terminal challenge attribution is incomplete")
		}
	}
	canonical, err := json.Marshal(values)
	if err != nil {
		return "", err
	}
	digest := sha256.New()
	digest.Write([]byte("terminal-attachment-challenge:v1"))
	digest.Write([]byte{0})
	digest.Write(canonical)
	digest.Write([]byte{0})
	var size [4]byte
	binary.BigEndian.PutUint32(size[:], uint32(len(challenge)))
	digest.Write(size[:])
	digest.Write(challenge)
	return "sha256:" + hex.EncodeToString(digest.Sum(nil)), nil
}

func CanonicalJSONFingerprint(namespace string, value any) (string, error) {
	if namespace == "" || strings.ContainsRune(namespace, 0) {
		return "", errors.New("invalid terminal JSON fingerprint namespace")
	}
	payload, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	digest := sha256.New()
	digest.Write([]byte(namespace))
	digest.Write([]byte{0})
	digest.Write(payload)
	return "sha256:" + hex.EncodeToString(digest.Sum(nil)), nil
}

func CanonicalProtobufJSONVectorBytes(values []*OperationalActivityCell) ([]byte, error) {
	canonical := make([]any, 0, len(values))
	for _, value := range values {
		if value == nil {
			return nil, errors.New("nil terminal protobuf JSON vector item")
		}
		encoded, err := (protojson.MarshalOptions{
			UseProtoNames:  true,
			UseEnumNumbers: true,
		}).Marshal(value)
		if err != nil {
			return nil, err
		}
		decoder := json.NewDecoder(bytes.NewReader(encoded))
		decoder.UseNumber()
		var normalized any
		if err := decoder.Decode(&normalized); err != nil {
			return nil, err
		}
		canonical = append(canonical, normalized)
	}
	return json.Marshal(canonical)
}

func OperationalActivityAccumulator(values []*OperationalActivityCell) (string, error) {
	accumulator, err := CanonicalJSONFingerprint("terminal-operational-activity-accumulator-genesis:v1", []any{})
	if err != nil {
		return "", err
	}
	for index, value := range values {
		common, err := operationalActivityCommon(value)
		if err != nil {
			return "", err
		}
		accumulator, err = CanonicalJSONFingerprint(
			"terminal-operational-activity-accumulator-step:v1",
			map[string]any{
				"activity_fingerprint": common.ActivityFingerprint,
				"coalesce_key":         common.CoalesceKey,
				"index":                index,
				"owner_generation":     common.OwnerGeneration,
				"owner_id":             common.OwnerId,
				"owner_kind":           common.OwnerKind,
				"previous_accumulator": accumulator,
			},
		)
		if err != nil {
			return "", err
		}
	}
	return accumulator, nil
}

func operationalActivityCommon(value *OperationalActivityCell) (*OperationalActivityCommon, error) {
	if value == nil {
		return nil, errors.New("operational activity cell is nil")
	}
	var common *OperationalActivityCommon
	switch item := value.Activity.(type) {
	case *OperationalActivityCell_ModelActivity:
		common = item.ModelActivity.GetCommon()
	case *OperationalActivityCell_ToolActivity:
		common = item.ToolActivity.GetCommon()
	case *OperationalActivityCell_TerminalProcessActivity:
		common = item.TerminalProcessActivity.GetCommon()
	case *OperationalActivityCell_SubagentActivity:
		common = item.SubagentActivity.GetCommon()
	default:
		return nil, errors.New("operational activity branch is unknown")
	}
	if common == nil {
		return nil, errors.New("operational activity common payload is missing")
	}
	return common, nil
}

func ConstantTimeBytesEqual(left, right []byte) bool {
	return bytes.Equal(left, right)
}
