// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: probe_wire/probe.proto

package probeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Lines         []string               `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_probe_wire_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_probe_wire_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_probe_wire_probe_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Snapshot) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SentUnixNanos int64                  `protobuf:"varint,3,opt,name=sent_unix_nanos,json=sentUnixNanos,proto3" json:"sent_unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_probe_wire_probe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_probe_wire_probe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_probe_wire_probe_proto_rawDescGZIP(), []int{1}
}

func (x *Delta) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Delta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Delta) GetSentUnixNanos() int64 {
	if x != nil {
		return x.SentUnixNanos
	}
	return 0
}

type ProbeFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ProbeFrame_Snapshot
	//	*ProbeFrame_Delta
	Body          isProbeFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeFrame) Reset() {
	*x = ProbeFrame{}
	mi := &file_probe_wire_probe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeFrame) ProtoMessage() {}

func (x *ProbeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_probe_wire_probe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeFrame.ProtoReflect.Descriptor instead.
func (*ProbeFrame) Descriptor() ([]byte, []int) {
	return file_probe_wire_probe_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeFrame) GetBody() isProbeFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProbeFrame) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Body.(*ProbeFrame_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ProbeFrame) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Body.(*ProbeFrame_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

type isProbeFrame_Body interface {
	isProbeFrame_Body()
}

type ProbeFrame_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type ProbeFrame_Delta struct {
	Delta *Delta `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

func (*ProbeFrame_Snapshot) isProbeFrame_Body() {}

func (*ProbeFrame_Delta) isProbeFrame_Body() {}

var File_probe_wire_probe_proto protoreflect.FileDescriptor

const file_probe_wire_probe_proto_rawDesc = "" +
	"\n" +
	"\x16probe_wire/probe.proto\x12\x13pulsara.terminal.s0\"<\n" +
	"\bSnapshot\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x14\n" +
	"\x05lines\x18\x02 \x03(\tR\x05lines\"e\n" +
	"\x05Delta\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12&\n" +
	"\x0fsent_unix_nanos\x18\x03 \x01(\x03R\rsentUnixNanos\"\x85\x01\n" +
	"\n" +
	"ProbeFrame\x12;\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1d.pulsara.terminal.s0.SnapshotH\x00R\bsnapshot\x122\n" +
	"\x05delta\x18\x02 \x01(\v2\x1a.pulsara.terminal.s0.DeltaH\x00R\x05deltaB\x06\n" +
	"\x04bodyB/Z-github.com/plumliu/pulsara-agent/clients/terminal-s0/internal/probeprotob\x06proto3"

var (
	file_probe_wire_probe_proto_rawDescOnce sync.Once
	file_probe_wire_probe_proto_rawDescData []byte
)

func file_probe_wire_probe_proto_rawDescGZIP() []byte {
	file_probe_wire_probe_proto_rawDescOnce.Do(func() {
		file_probe_wire_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_probe_wire_probe_proto_rawDesc), len(file_probe_wire_probe_proto_rawDesc)))
	})
	return file_probe_wire_probe_proto_rawDescData
}

var file_probe_wire_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_probe_wire_probe_proto_goTypes = []any{
	(*Snapshot)(nil),   // 0: pulsara.terminal.s0.Snapshot
	(*Delta)(nil),      // 1: pulsara.terminal.s0.Delta
	(*ProbeFrame)(nil), // 2: pulsara.terminal.s0.ProbeFrame
}
var file_probe_wire_probe_proto_depIdxs = []int32{
	0, // 0: pulsara.terminal.s0.ProbeFrame.snapshot:type_name -> pulsara.terminal.s0.Snapshot
	1, // 1: pulsara.terminal.s0.ProbeFrame.delta:type_name -> pulsara.terminal.s0.Delta
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_probe_wire_probe_proto_init() }
func file_probe_wire_probe_proto_init() {
	if File_probe_wire_probe_proto != nil {
		return
	}
	file_probe_wire_probe_proto_msgTypes[2].OneofWrappers = []any{
		(*ProbeFrame_Snapshot)(nil),
		(*ProbeFrame_Delta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_probe_wire_probe_proto_rawDesc), len(file_probe_wire_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_probe_wire_probe_proto_goTypes,
		DependencyIndexes: file_probe_wire_probe_proto_depIdxs,
		MessageInfos:      file_probe_wire_probe_proto_msgTypes,
	}.Build()
	File_probe_wire_probe_proto = out.File
	file_probe_wire_probe_proto_goTypes = nil
	file_probe_wire_probe_proto_depIdxs = nil
}
