"""Shared explicit test doubles."""

from tests.support.model_call import (
    bind_test_context,
    bind_test_provider_input_context,
    context_compiled_contract_fields,
    compaction_completed_contract_fields,
    compaction_failed_contract_fields,
    compaction_started_contract_fields,
    model_call_end_fields,
    model_call_start_fields,
    make_test_run_execution_activation,
    resolve_test_call,
    run_agent_task,
    start_test_direct_model_stream,
    stream_agent_task,
    test_llm_config,
    test_llm_context,
    test_model_limits,
    test_model_slot,
    test_resolved_call_fact,
    test_resolved_call,
    test_resolved_target_fact,
)
from tests.support.postgres import (
    UnverifiedTestPostgresAccessLease,
    UnverifiedTestPostgresConnectionProvider,
    unverified_test_postgres_access_lease,
    verified_postgres_access_lease,
    verified_postgres_provider,
)

__all__ = [
    "bind_test_context",
    "bind_test_provider_input_context",
    "context_compiled_contract_fields",
    "compaction_completed_contract_fields",
    "compaction_failed_contract_fields",
    "compaction_started_contract_fields",
    "model_call_end_fields",
    "model_call_start_fields",
    "make_test_run_execution_activation",
    "resolve_test_call",
    "run_agent_task",
    "start_test_direct_model_stream",
    "stream_agent_task",
    "test_llm_config",
    "test_llm_context",
    "test_model_limits",
    "test_model_slot",
    "test_resolved_call_fact",
    "test_resolved_call",
    "test_resolved_target_fact",
    "UnverifiedTestPostgresAccessLease",
    "UnverifiedTestPostgresConnectionProvider",
    "unverified_test_postgres_access_lease",
    "verified_postgres_access_lease",
    "verified_postgres_provider",
]
