"""Immutable context-input collection and preparation services."""

from pulsara_agent.runtime.context_input.candidate import (
    ContextLifecycleCachePort,
    ContextLifecycleCacheOperationalDiagnostic,
    ContextLifecycleCacheWriteCandidate,
    InMemoryContextLifecycleCache,
    PreparedContextCandidateCollection,
    DEFAULT_SYSTEM_PROMPT,
    ContextCandidateCollectionInput,
    build_context_candidate_authorities,
    build_context_candidate_source_selections,
    collect_context_candidates,
    prepare_context_candidates,
    render_plan_revision_instruction,
    render_runtime_context_from_facts,
    validate_candidate_against_snapshot,
)

from pulsara_agent.runtime.context_input.event_slice import (
    ContextEventSlice,
    ContextEventSliceError,
    ContextEventSliceReader,
    EventLogContextEventSliceReader,
    FrozenStoredEvent,
    event_reference_from_stored,
)
from pulsara_agent.runtime.context_input.io_service import (
    ContextInputIoDeadlineExceeded,
    ContextInputIoService,
    PendingContextInputIoError,
)
from pulsara_agent.runtime.context_input.policy import resolve_context_compile_policy
from pulsara_agent.runtime.context_input.live import (
    ContextInputPreparationError,
    PreparedLiveContextSnapshot,
    PreparedLiveTranscriptProjection,
    collect_live_context_inputs,
    collect_context_projection_references,
    descriptor_render_attribution,
    prepare_live_context_snapshot,
    prepare_live_transcript_projection,
)
from pulsara_agent.runtime.context_input.manifest import (
    ContextInputManifestConfirmedAbsent,
    ContextInputManifestWriteCandidate,
    ContextInputManifestWriteConflict,
    ContextInputManifestWriteDeadlineExceeded,
    ContextInputManifestWriteOutcomeUnknown,
    ContextInputManifestWriteResult,
    ContextInputManifestWriteService,
    PendingContextInputManifestWriteError,
    build_context_compile_input_audit,
    build_context_input_manifest,
    build_context_input_manifest_candidate,
)
from pulsara_agent.runtime.context_input.render import (
    InMemoryToolResultRenderCache,
    PreparedToolResultRenderOutput,
    RenderedToolResultFragment,
    ToolResultRenderCacheWriteCandidate,
    ToolResultRenderDecisionCachePort,
    prepare_tool_result_render_input,
    render_prepared_tool_result_units,
    validate_prepared_tool_result_render_output,
)
from pulsara_agent.runtime.context_input.compiler import (
    LoweredTranscriptMessages,
    canonical_render_decisions_fingerprint,
    compile_context_from_facts,
    lower_transcript_for_context,
    provider_neutral_payload_fingerprint,
)
from pulsara_agent.runtime.context_input.external import (
    ExternalToolResultIngressBuilder,
    freeze_external_tool_result_submission,
)
from pulsara_agent.runtime.context_input.snapshot import (
    ContextFactSnapshot,
    ContextSnapshotBuildInput,
    bind_context_invocation,
    build_context_snapshot,
    collect_replay_context_inputs,
    finalize_context_authority_slice_plan,
)
from pulsara_agent.runtime.context_input.transcript import (
    NormalizedContextTranscript,
    ToolResultPairingError,
    TranscriptNormalizationError,
    project_context_transcript,
)
from pulsara_agent.runtime.context_input.replay import (
    ContextInputReplayError,
    ContextInputReplayStatus,
    ReplayedCompiledContext,
    ReplayedContextInput,
    load_context_input_manifest,
    replay_context_input,
    replay_compiled_context,
)

__all__ = [
    "DEFAULT_SYSTEM_PROMPT",
    "ContextEventSlice",
    "ContextEventSliceError",
    "ContextEventSliceReader",
    "ContextFactSnapshot",
    "ContextInputManifestConfirmedAbsent",
    "ContextInputPreparationError",
    "ContextInputIoDeadlineExceeded",
    "ContextInputIoService",
    "ContextInputManifestWriteCandidate",
    "ContextInputManifestWriteConflict",
    "ContextInputManifestWriteDeadlineExceeded",
    "ContextInputManifestWriteOutcomeUnknown",
    "ContextInputManifestWriteResult",
    "ContextInputManifestWriteService",
    "ContextLifecycleCachePort",
    "ContextLifecycleCacheOperationalDiagnostic",
    "ContextLifecycleCacheWriteCandidate",
    "InMemoryContextLifecycleCache",
    "InMemoryToolResultRenderCache",
    "ContextInputReplayError",
    "ContextInputReplayStatus",
    "ContextSnapshotBuildInput",
    "EventLogContextEventSliceReader",
    "ExternalToolResultIngressBuilder",
    "FrozenStoredEvent",
    "NormalizedContextTranscript",
    "PreparedLiveContextSnapshot",
    "PreparedLiveTranscriptProjection",
    "PreparedContextCandidateCollection",
    "PreparedToolResultRenderOutput",
    "RenderedToolResultFragment",
    "ToolResultRenderCacheWriteCandidate",
    "LoweredTranscriptMessages",
    "ReplayedContextInput",
    "ReplayedCompiledContext",
    "PendingContextInputManifestWriteError",
    "PendingContextInputIoError",
    "ContextCandidateCollectionInput",
    "build_context_candidate_authorities",
    "build_context_candidate_source_selections",
    "ToolResultPairingError",
    "ToolResultRenderDecisionCachePort",
    "TranscriptNormalizationError",
    "bind_context_invocation",
    "build_context_snapshot",
    "build_context_compile_input_audit",
    "build_context_input_manifest",
    "build_context_input_manifest_candidate",
    "collect_replay_context_inputs",
    "collect_live_context_inputs",
    "collect_context_projection_references",
    "collect_context_candidates",
    "compile_context_from_facts",
    "lower_transcript_for_context",
    "canonical_render_decisions_fingerprint",
    "descriptor_render_attribution",
    "event_reference_from_stored",
    "finalize_context_authority_slice_plan",
    "freeze_external_tool_result_submission",
    "load_context_input_manifest",
    "prepare_live_context_snapshot",
    "prepare_live_transcript_projection",
    "prepare_context_candidates",
    "render_plan_revision_instruction",
    "render_runtime_context_from_facts",
    "provider_neutral_payload_fingerprint",
    "prepare_tool_result_render_input",
    "validate_candidate_against_snapshot",
    "render_prepared_tool_result_units",
    "project_context_transcript",
    "replay_context_input",
    "replay_compiled_context",
    "resolve_context_compile_policy",
    "validate_prepared_tool_result_render_output",
]
