# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: probe_wire/probe.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 34, 0, "", "probe_wire/probe.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16probe_wire/probe.proto\x12\x13pulsara.terminal.s0"+\n\x08Snapshot\x12\x10\n\x08revision\x18\x01 \x01(\x04\x12\r\n\x05lines\x18\x02 \x03(\t"C\n\x05\x44\x65lta\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x17\n\x0fsent_unix_nanos\x18\x03 \x01(\x03"t\n\nProbeFrame\x12\x31\n\x08snapshot\x18\x01 \x01(\x0b\x32\x1d.pulsara.terminal.s0.SnapshotH\x00\x12+\n\x05\x64\x65lta\x18\x02 \x01(\x0b\x32\x1a.pulsara.terminal.s0.DeltaH\x00\x42\x06\n\x04\x62odyB/Z-pulsara.local/terminal-s0/internal/probeprotob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "probe_wire.probe_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"Z-pulsara.local/terminal-s0/internal/probeproto"
    _globals["_SNAPSHOT"]._serialized_start = 47
    _globals["_SNAPSHOT"]._serialized_end = 90
    _globals["_DELTA"]._serialized_start = 92
    _globals["_DELTA"]._serialized_end = 159
    _globals["_PROBEFRAME"]._serialized_start = 161
    _globals["_PROBEFRAME"]._serialized_end = 277
# @@protoc_insertion_point(module_scope)
